# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generates the per-version glue pywrap packages for the multi-ABI wheel.

Each PyTorch version in WHEEL_TORCH_VERSIONS gets its own bazel package for its
`pywrap_library`: the shared xla_base common library must keep the same target
name (and hence `libxla_base.so` basename) in every version, so two versions
cannot share a package. The packages are identical bar the version encoded in
the package name, so rather than checking one in per version, this repository
rule writes them all under `@torch_tpu_glues`, keeping the version list
single-sourced in //bazel:pytorch_versions.bzl. See
//bazel:glue.bzl for the package contents.
"""

load("//bazel:pytorch_versions.bzl", "WHEEL_TORCH_VERSIONS")

# Main-repo labels resolved here (a main-repo .bzl) so their canonical form can
# be spliced into the generated BUILD files, where plain "//..." labels would
# resolve to the generated repository instead.
_GLUE_BZL = Label("//bazel:glue.bzl")
_LICENSE = Label("//:license")

_BUILD_TEMPLATE = """\
# Generated by //bazel:glue_packages.bzl. The PyTorch version comes from this
# package's name (glue_2_11_0 -> 2.11.0); versioned_glue_library supplies the
# rest. See //bazel:glue.bzl and //shims/pybind11:pybind.bzl.
load("{glue_bzl}", "versioned_glue_library")

package(
    default_applicable_licenses = ["{license}"],
    default_visibility = ["//visibility:public"],
)

versioned_glue_library()
"""

def _glue_packages_impl(rctx):
    rctx.file("BUILD", "")
    for version in WHEEL_TORCH_VERSIONS:
        suffix = version.replace(".", "_")
        rctx.file(
            "torch_tpu/common/glue_{}/BUILD".format(suffix),
            _BUILD_TEMPLATE.format(glue_bzl = _GLUE_BZL, license = _LICENSE),
        )

glue_packages = repository_rule(
    implementation = _glue_packages_impl,
    doc = "One glue pywrap package per PyTorch version in WHEEL_TORCH_VERSIONS.",
)
