module(
    name = "torch_tpu",
    version = "0.1.1",
)

SUPPORTED_PYTHON_VERSIONS = [
    "3.11",
    "3.12",
    "3.13",
    "3.14",
]

# BCR dependencies
bazel_dep(name = "abseil-cpp", version = "20260107.1", repo_name = "com_google_absl")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "curl", version = "8.11.0")
bazel_dep(name = "rules_cc", version = "0.2.9")
bazel_dep(name = "rules_python", version = "1.8.5")
bazel_dep(name = "rules_proto", version = "7.1.0")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "protobuf", version = "32.1", repo_name = "com_google_protobuf")
bazel_dep(name = "googletest", version = "1.15.2", repo_name = "com_google_googletest")
bazel_dep(name = "grpc", version = "1.78.0", repo_name = "com_github_grpc_grpc")
bazel_dep(name = "googleapis", version = "0.0.0-20240819-fe8ba054a")
bazel_dep(name = "re2", version = "2025-11-05.bcr.1", repo_name = "com_googlesource_code_re2")

# BCR overrides

single_version_override(
    module_name = "curl",
    patches = ["//bazel/patches/curl:remove_linker_script.patch"],
    version = "8.11.0",
)

single_version_override(
    module_name = "rules_python",
    patch_strip = 1,
    patches = [
        "//bazel/patches/rules_python:rules_python_pip_version.patch",
        "//bazel/patches/rules_python:rules_python_freethreaded.patch",
        "//bazel/patches/rules_python:rules_python_versions.patch",
        "//bazel/patches/rules_python:rules_python_scope.patch",
    ],
    version = "1.8.5",
)

single_version_override(
    module_name = "grpc",
    patch_strip = 1,
    patches = ["//bazel/patches/grpc:grpc.patch"],
    version = "1.78.0",
)

# TODO(ecalubaquib): Remove once googleapis is updated to a version compatible with current
# rules_python. This will allow us to run bazel mod graph
single_version_override(
    module_name = "googleapis",
    version = "0.0.0-20240819-fe8ba054a",
)

# Non-BCR or specific commit modules
bazel_dep(name = "xla")
bazel_dep(name = "rules_ml_toolchain")

archive_override(
    module_name = "xla",
    integrity = "sha256-6103a9hGp02vVtT6Xavw7r/Ix0uAvK1U+/Iic2croiM=",
    patch_strip = 1,
    patches = ["//bazel/patches/xla:xla_bazel8.patch"],
    strip_prefix = "xla-1e42a8527caa67e59827034e2d6371d965e9a1e8",
    urls = ["https://github.com/openxla/xla/archive/1e42a8527caa67e59827034e2d6371d965e9a1e8.tar.gz"],
)

archive_override(
    module_name = "rules_ml_toolchain",
    integrity = "sha256-koXZBgF1eDjQZKEvUfFDdNQAZN3C+hmJeZCLa9D4k0g=",
    strip_prefix = "rules_ml_toolchain-7f40603f574b95746152332ef3ad5fce63f1768d",
    urls = ["https://github.com/google-ml-infra/rules_ml_toolchain/archive/7f40603f574b95746152332ef3ad5fce63f1768d.tar.gz"],
)

archive_override(
    module_name = "googletest",
    integrity = "sha256-8lPKGgcmL4796DKOSyxol55A3fz8AB9w0dX2EsfeKXQ=",
    strip_prefix = "googletest-28e9d1f26771c6517c3b4be10254887673c94018",
    urls = ["https://github.com/google/googletest/archive/28e9d1f26771c6517c3b4be10254887673c94018.zip"],
)

##############################################################
# Dependencies defined in XLA via module extensions
##############################################################

### TSL
tsl_extension = use_extension("@xla//third_party/extensions:tsl.bzl", "tsl_extension")
use_repo(tsl_extension, "tsl")

llvm = use_extension("@xla//third_party/extensions:llvm.bzl", "llvm_extension")
use_repo(llvm, "llvm-project")

### C++ dependencies
# TODO: convert them to Bazel modules (bazel_dep).
third_party = use_extension("@xla//third_party/extensions:third_party.bzl", "third_party_ext")
use_repo(
    third_party,
    "dlpack",
    "eigen_archive",
    "gloo",
    "nanobind",
    "shardy",
    "stablehlo",
    "triton",
)

# Python extension
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.defaults(
    python_version = "3.12",
    python_version_env = "HERMETIC_PYTHON_VERSION",
)

[python.toolchain(
    python_version = v,
) for v in SUPPORTED_PYTHON_VERSIONS]

[use_repo(
    python,
    "python_" + v.replace(".", "_"),
) for v in SUPPORTED_PYTHON_VERSIONS]

# Pip extension
pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")

[pip.parse(
    extra_hub_aliases = {
        "torch": [
            "torch_headers",
            "torch_libs",
            "libc10",
            "libtorch_cpu",
            "libtorch_python",
            "libtorch",
            "libshm",
            "libtorch_global_deps",
        ],
    },
    extra_pip_args = [
        "--index-url",
        "https://pypi.org/simple",
        "--extra-index-url",
        "https://download.pytorch.org/whl/cpu",
    ],
    hub_name = "torch_tpu_pypi",
    python_version = python_version,
    requirements_lock = "//requirements:requirements_{}.txt".format(python_version.replace(".", "_")),
    whl_modifications = {
        "//bazel:torch_wheel.json": "torch",
    },
) for python_version in SUPPORTED_PYTHON_VERSIONS]

# Expose the pip repositories using the names your BUILD files expect
use_repo(pip, pypi = "torch_tpu_pypi")

[use_repo(
    pip,
    **{
        "pypi_libtpu_" + v.replace(".", ""): "torch_tpu_pypi_" + v.replace(".", "") + "_libtpu",
        "pypi_torch_" + v.replace(".", ""): "torch_tpu_pypi_" + v.replace(".", "") + "_torch",
    }
) for v in SUPPORTED_PYTHON_VERSIONS]

# Custom repository rules
torch_local_repo = use_repo_rule("//bazel:torch_local_repo.bzl", "torch_local_repo")

torch_local_repo(
    name = "local_torch",
)

torch_tpu_version_repo = use_repo_rule("//bazel:wheel_version.bzl", "torch_tpu_version_repo")

torch_tpu_version_repo(
    name = "torch_tpu_version",
    pyproject_toml = "//:pyproject.toml",
)

# Load and run the custom extension
torch_tpu_ext = use_extension("//bazel:extensions.bzl", "torch_tpu_deps_ext")

# Expose the generated repository to your BUILD files
use_repo(torch_tpu_ext, "torch_tpu_deps")

# RBE
rbe_config = use_extension("@xla//third_party/extensions:rbe_config.bzl", "rbe_config_ext")
use_repo(rbe_config, "ml_build_config_platform")

# Ensure Bazel securely mounts the ThreadSanitizer runtime library into the RBE sandbox runfiles.
http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "tsan_lib",
    downloaded_file_path = "libclang_rt.tsan.so",
    sha256 = "4495aec33d1d6b56785af7d36d2b3b1801ece4ff53db43fc83a2a7fcede97dfe",
    urls = ["https://storage.googleapis.com/ml-sysroot-testing/python/libclang_rt.tsan-llvm20-20260511.so"],
)
