# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: b/431034055 - add build-system when OSS build working
[project]
name = "torch_tpu"
version = "0.1.1"
license = "Apache-2.0"
license-files = ["LICENSE"]

dependencies = [
    "torch>=2.11.0",
    "numpy>=2",
    "absl-py>=2",
    "libtpu>=0.0.40",
    "portpicker>=1.6",
    "tensorboard>=2.20",
    "frozendict>=2",
    "immutabledict>=4",
]

[project.optional-dependencies]
dev = [
    "accelerate>=1.12",
    "etils[epath]>=1.14",
    "expecttest>=0.3",
    "jax >= 0.9.2",
    "transformers>=5.8.0",
]

test = [
    "pillow>=11.3.0",
    "scipy>=1.16.1",
    "numpy>=2",
    "timm>=1.0.26",
    "torchvision>=0.25",
    "transformers>=5.8.0",
]

benchmark = [
    "fairscale>=0.4",
    "flax>=0.12",
    "grain>=0.2.16",
    "llama-models>=0.3.0",
    "tensorflow-datasets>=4.9.9",
    "tensorboardx>=2.6",
    "timm>=1.0.26",
    "torchax>=0.0.11",
    "grpcio-tools>=1.80.0",
    "dm-tree>=0.1.10"
]

examples = [
    "datasets>=4.8",
    "pillow>=11",
    "tqdm>=4",
    "huggingface-hub>=0.34",
    "transformers>=5.8.0",
    "diffusers>=0.37",
    "peft>=0.18",
    "torchvision>=0.25",
    "llama-models>=0.3.0",
    "fairscale>=0.4",
    "grain>=0.2.16",
    "tensorflow-datasets>=4.9.9",
    "accelerate>=1.12",
    "jax >= 0.9.2",
    "matplotlib>=3.11.0",
    "tqdm>=4",
    "flax>=0.12",
    "tensorboardx>=2.6",
    "torchax>=0.0.11"
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }
