# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Ops that are missing a required C++ registration.

This list contains ops from native_functions.yaml that are required to be
registered by the logic in native_functions_test.py, but do not have a
corresponding C++ registration in tpu_aten_kernels.cc.

This is a temporary list that should be emptied, either by adding a C++
registration for the op, or by adjusting the logic in native_functions_test.py
that determines which ops need a C++ registration.
"""

UNREGISTERED_OPS = frozenset([
    # go/keep-sorted start
    '_addmm_activation.out',
    '_aminmax',
    '_aminmax.dim',
    '_amp_foreach_non_finite_check_and_unscale_',
    '_amp_update_scale_',
    '_batch_norm_with_update',
    '_batch_norm_with_update.out',
    '_cholesky_solve_helper',
    '_coalesce',
    '_coalesced_',
    '_compute_linear_combination',
    '_compute_linear_combination.out',
    '_conv_depthwise2d',
    '_conv_depthwise2d.out',
    '_convert_indices_from_coo_to_csr.out',
    '_convert_indices_from_csr_to_coo.out',
    '_convert_weight_to_int4pack',
    '_convert_weight_to_int4pack_for_cpu',
    '_cslt_compress',
    '_cslt_sparse_mm',
    '_cslt_sparse_mm_search',
    '_dimI',
    '_dimV',
    '_dirichlet_grad',
    '_dyn_quant_matmul_4bit',
    '_dyn_quant_pack_4bit_weight',
    '_efficient_attention_backward',
    '_efficient_attention_forward',
    '_embedding_bag_dense_backward',
    '_embedding_bag_per_sample_weights_backward',
    '_empty_affine_quantized',
    '_empty_per_channel_affine_quantized',
    '_fake_quantize_learnable_per_channel_affine',
    '_fake_quantize_learnable_per_channel_affine_backward',
    '_fake_quantize_learnable_per_tensor_affine',
    '_fake_quantize_learnable_per_tensor_affine_backward',
    '_fake_quantize_per_tensor_affine_cachemask_tensor_qparams',
    '_fill_mem_eff_dropout_mask_',
    '_flash_attention_backward',
    '_flash_attention_forward',
    '_flash_attention_forward.quantized',
    '_flash_attention_forward_no_dropout_inplace',
    '_functional_assert_async.msg',
    '_fused_adagrad_',
    '_fused_adagrad_.tensor_lr',
    '_fused_adam_',
    '_fused_adam_.tensor_lr',
    '_fused_adamw_',
    '_fused_adamw_.tensor_lr',
    '_fused_dropout',
    '_fused_moving_avg_obs_fq_helper',
    '_fused_sdp_choice',
    '_fused_sgd_',
    '_fused_sgd_.tensor_lr',
    '_histogramdd_bin_edges',
    '_histogramdd_from_bin_cts',
    '_histogramdd_from_bin_tensors',
    '_indices',
    '_int_mm',
    '_int_mm.out',
    '_jagged_to_padded_dense_forward',
    '_linalg_det.result',
    '_linalg_eigh.eigenvalues',
    '_linalg_eigvals',
    '_linalg_slogdet.sign',
    '_linalg_svd.U',
    '_logcumsumexp',
    '_logcumsumexp.out',
    '_lstm_mps',
    '_make_dep_token',
    '_make_per_channel_quantized_tensor',
    '_make_per_tensor_quantized_tensor',
    '_masked_scale',
    '_masked_softmax',
    '_masked_softmax_backward',
    '_mixed_dtypes_linear',
    '_mkldnn_reshape',
    '_mkldnn_transpose',
    '_mkldnn_transpose_',
    '_mps_convolution',
    '_mps_convolution_transpose',
    '_native_multi_head_attention',
    '_nested_compute_contiguous_strides_offsets',
    '_nested_from_padded',
    '_nested_from_padded_and_nested_example',
    '_nested_from_padded_tensor',
    '_nested_get_jagged_dummy',
    '_nested_get_lengths',
    '_nested_get_max_seqlen',
    '_nested_get_min_seqlen',
    '_nested_get_offsets',
    '_nested_get_ragged_idx',
    '_nested_get_values',
    '_nested_select_backward',
    '_nested_sum_backward',
    '_nested_tensor_from_mask',
    '_nested_tensor_from_mask_left_aligned',
    '_nested_tensor_size',
    '_nested_tensor_softmax_with_shape',
    '_nested_tensor_storage_offsets',
    '_nested_tensor_strides',
    '_nested_view_from_buffer',
    '_nested_view_from_jagged',
    '_nnz',
    '_padded_dense_to_jagged_forward',
    '_philox_key_fold_in',
    '_philox_key_split',
    '_philox_normal_',
    '_philox_uniform_',
    '_prelu_kernel',
    '_prelu_kernel_backward',
    '_resize_output_',
    '_sample_dirichlet',
    '_scaled_dot_product_attention_math_for_mps',
    '_scaled_dot_product_efficient_attention_backward',
    '_scaled_dot_product_flash_attention',
    '_scaled_dot_product_flash_attention.quantized',
    '_scaled_dot_product_flash_attention_backward',
    '_scaled_grouped_mm',
    '_scaled_grouped_mm_v2',
    '_scaled_mm_v2',
    '_scaled_mm_v2.out',
    '_segment_reduce_backward',
    '_slow_conv2d_backward.grad_input',
    '_slow_conv2d_backward.output_mask',
    '_slow_conv2d_forward',
    '_slow_conv2d_forward.output',
    '_sparse_broadcast_to',
    '_sparse_coo_tensor_with_dims',
    '_sparse_coo_tensor_with_dims_and_tensors',
    '_sparse_csr_prod.dim_dtype',
    '_sparse_csr_sum.dim_dtype',
    '_sparse_log_softmax',
    '_sparse_log_softmax_backward_data',
    '_sparse_mask_projection',
    '_sparse_mm_reduce_impl',
    '_sparse_mm_reduce_impl_backward',
    '_sparse_semi_structured_addmm',
    '_sparse_semi_structured_apply',
    '_sparse_semi_structured_apply_dense',
    '_sparse_semi_structured_linear',
    '_sparse_semi_structured_mm',
    '_sparse_semi_structured_tile',
    '_sparse_softmax',
    '_sparse_softmax_backward_data',
    '_sparse_sparse_matmul',
    '_sparse_sum_backward',
    '_spdiags',
    '_spsolve',
    '_standard_gamma',
    '_standard_gamma_grad',
    '_thnn_fused_gru_cell',
    '_thnn_fused_gru_cell_backward',
    '_thnn_fused_lstm_cell',
    '_thnn_fused_lstm_cell_backward_impl',
    '_to_dense',
    '_to_sparse',
    '_to_sparse.sparse_dim',
    '_to_sparse_bsc',
    '_to_sparse_bsr',
    '_to_sparse_csc',
    '_to_sparse_csr',
    '_to_sparse_semi_structured',
    '_transform_bias_rescale_qkv',
    '_transformer_encoder_layer_fwd',
    '_triton_multi_head_attention',
    '_triton_scaled_dot_attention',
    '_unique',
    '_upsample_bicubic2d_aa.out',
    '_upsample_bicubic2d_aa_backward.grad_input',
    '_upsample_bilinear2d_aa.out',
    '_upsample_bilinear2d_aa_backward.grad_input',
    '_upsample_lanczos2d_aa.out',
    '_upsample_lanczos2d_aa_backward.grad_input',
    '_use_miopen_ctc_loss',
    '_use_miopen_ctc_loss.Tensor',
    '_validate_compressed_sparse_indices',
    '_values',
    '_weight_int4pack_mm',
    '_weight_int4pack_mm_for_cpu',
    '_weight_int4pack_mm_with_scales_and_zeros',
    '_weight_int8pack_mm',
    '_weight_norm_interface_backward',
    'adaptive_max_pool2d.out',
    'adaptive_max_pool2d_backward.grad_input',
    'adaptive_max_pool3d.out',
    'adaptive_max_pool3d_backward.grad_input',
    'addbmm',
    'addbmm.out',
    'addbmm_',
    'angle',
    'angle.out',
    'batch_norm_backward',
    'batch_norm_backward_elemt',
    'batch_norm_backward_reduce',
    'batch_norm_elemt',
    'batch_norm_elemt.out',
    'batch_norm_gather_stats',
    'batch_norm_gather_stats_with_counts',
    'batch_norm_stats',
    'batch_norm_update_stats',
    'binary_cross_entropy',
    'binary_cross_entropy.out',
    'binary_cross_entropy_backward',
    'binary_cross_entropy_backward.grad_input',
    'binomial',
    'cauchy_',
    'channel_shuffle',
    'cholesky',
    'cholesky.out',
    'cholesky_inverse',
    'cholesky_inverse.out',
    'conv_depthwise3d',
    'copy_sparse_to_sparse_',
    'copysign.out',
    'count_nonzero.dim_IntList',
    'dequantize.self',
    'dequantize.tensors',
    'empty_quantized',
    'erfc.out',
    'fake_quantize_per_channel_affine_cachemask',
    'frac.out',
    'fractional_max_pool2d.output',
    'fractional_max_pool2d_backward.grad_input',
    'fractional_max_pool3d.output',
    'fractional_max_pool3d_backward',
    'fractional_max_pool3d_backward.grad_input',
    'frexp.Tensor_out',
    'from_file',
    'gcd.out',
    'geometric_',
    'glu_backward_jvp',
    'glu_jvp',
    'hardshrink.out',
    'hardshrink_backward.grad_input',
    'hash_tensor.out',
    'heaviside.out',
    'histogram.bin_ct',
    'histogram.bin_ct_out',
    'histogram.bins_tensor',
    'histogram.bins_tensor_out',
    'hspmm',
    'hspmm.out',
    'huber_loss',
    'huber_loss.out',
    'huber_loss_backward.out',
    'hypot.out',
    'i0.out',
    'igamma.out',
    'igammac.out',
    'index_select.out',
    'int_repr',
    'is_set_to',
    'kthvalue.values',
    'lcm.out',
    'linalg_cholesky_ex.L',
    'linalg_cross.out',
    'linalg_eig',
    'linalg_eig.out',
    'linalg_eigvals.out',
    'linalg_householder_product',
    'linalg_householder_product.out',
    'linalg_ldl_factor_ex.out',
    'linalg_ldl_solve.out',
    'linalg_lstsq.out',
    'linalg_matrix_exp',
    'linear_backward',
    'log_normal_',
    'logaddexp.out',
    'logaddexp2.out',
    'logit',
    'logit.out',
    'logit_',
    'logit_backward.grad_input',
    'logspace.out',
    'lstm_mps_backward',
    'matmul_backward',  # No need to register as matmul is an optional op
    'max_pool2d_backward',
    'max_unpool2d',
    'max_unpool2d.out',
    'max_unpool3d',
    'max_unpool3d.out',
    'median',
    'median.dim_values',
    'miopen_batch_norm',
    'miopen_batch_norm_backward',
    'miopen_convolution',
    'miopen_convolution_add_relu',
    'miopen_convolution_relu',
    'miopen_convolution_transpose',
    'miopen_ctc_loss',
    'miopen_ctc_loss.Tensor',
    'miopen_depthwise_convolution',
    'miopen_rnn',
    'miopen_rnn_backward',
    'mish.out',
    'mkldnn_adaptive_avg_pool2d',
    'mkldnn_adaptive_avg_pool2d.out',
    'mkldnn_adaptive_avg_pool2d_backward',
    'mkldnn_linear',
    'mkldnn_linear_backward',
    'mkldnn_linear_backward_input',
    'mkldnn_linear_backward_weights',
    'mkldnn_max_pool2d',
    'mkldnn_max_pool2d_backward',
    'mkldnn_max_pool3d',
    'mkldnn_max_pool3d_backward',
    'mkldnn_reorder_conv2d_weight',
    'mkldnn_reorder_conv3d_weight',
    'mkldnn_rnn_layer',
    'mkldnn_rnn_layer_backward',
    'mode',
    'mps_convolution_backward',
    'mps_convolution_transpose_backward',
    'mse_loss_backward.grad_input',
    'multi_margin_loss',
    'multi_margin_loss.out',
    'multi_margin_loss_backward',
    'multi_margin_loss_backward.grad_input',
    'multilabel_margin_loss_backward',
    'multilabel_margin_loss_backward.grad_input',
    'multilabel_margin_loss_forward',
    'multilabel_margin_loss_forward.output',
    'mvlgamma.out',
    'nanmedian',
    'nanmedian.dim_values',
    'nansum',
    'nansum.out',
    'narrow_copy.out',
    'native_norm',
    'native_norm.ScalarOpt_dim_dtype',
    'nextafter.out',
    'nonzero_static',
    'nonzero_static.out',
    'norm.dtype_out',
    'norm.out',
    'ormqr',
    'ormqr.out',
    'poisson',
    'polygamma.out',
    'q_per_channel_axis',
    'q_per_channel_scales',
    'q_per_channel_zero_points',
    'q_scale',
    'q_zero_point',
    'qscheme',
    'quantize_per_channel',
    'quantize_per_tensor',
    'quantize_per_tensor.tensor_qparams',
    'quantize_per_tensor.tensors',
    'quantize_per_tensor_dynamic',
    'quantized_batch_norm',
    'quantized_max_pool1d',
    'quantized_max_pool2d',
    'quantized_max_pool3d',
    'range.out',
    'record_stream',
    'renorm.out',
    'repeat_interleave.Tensor',
    'resize_as_sparse_',
    'rrelu_with_noise',
    'rrelu_with_noise.out',
    'rrelu_with_noise_',
    'searchsorted.Scalar',
    'searchsorted.Scalar_out',
    'searchsorted.Tensor',
    'searchsorted.Tensor_out',
    'segment_reduce',
    'silu_backward.grad_input',
    'sinc.out',
    'slow_conv3d_forward',
    'slow_conv3d_forward.output',
    'slow_conv_dilated2d',
    'slow_conv_dilated3d',
    'slow_conv_transpose2d.out',
    'slow_conv_transpose3d',
    'slow_conv_transpose3d.out',
    'smooth_l1_loss.out',
    'smooth_l1_loss_backward.grad_input',
    'softshrink.out',
    'softshrink_backward.grad_input',
    'sparse_mask',
    'sparse_resize_',
    'sparse_resize_and_clear_',
    'sparse_sampled_addmm',
    'sparse_sampled_addmm.out',
    'special_airy_ai.out',
    'special_bessel_j0.out',
    'special_bessel_j1.out',
    'special_bessel_y0.out',
    'special_bessel_y1.out',
    'special_chebyshev_polynomial_t.out',
    'special_chebyshev_polynomial_u.out',
    'special_chebyshev_polynomial_v.out',
    'special_chebyshev_polynomial_w.out',
    'special_entr.out',
    'special_erfcx.out',
    'special_hermite_polynomial_h.out',
    'special_hermite_polynomial_he.out',
    'special_i0e.out',
    'special_i1.out',
    'special_i1e.out',
    'special_laguerre_polynomial_l.out',
    'special_legendre_polynomial_p.out',
    'special_log_ndtr.out',
    'special_modified_bessel_i0.out',
    'special_modified_bessel_i1.out',
    'special_modified_bessel_k0.out',
    'special_modified_bessel_k1.out',
    'special_ndtri.out',
    'special_scaled_modified_bessel_k0.out',
    'special_scaled_modified_bessel_k1.out',
    'special_shifted_chebyshev_polynomial_t.out',
    'special_shifted_chebyshev_polynomial_u.out',
    'special_shifted_chebyshev_polynomial_v.out',
    'special_shifted_chebyshev_polynomial_w.out',
    'special_spherical_bessel_j0.out',
    'special_xlog1py.out',
    'special_zeta.out',
    'sspaddmm.out',
    'std.correction',
    'std.correction_out',
    'std_mean.correction',
    'to_mkldnn',
    'to_padded_tensor',
    'trace',
    'triangular_solve.X',
    'triu_indices',
    'unique_consecutive',
    'unique_dim',
    'unique_dim_consecutive',
    'upsample_bicubic2d.out',
    'upsample_bicubic2d_backward.grad_input',
    'upsample_linear1d.out',
    'upsample_linear1d_backward.grad_input',
    'upsample_trilinear3d.out',
    'upsample_trilinear3d_backward.grad_input',
    'var_mean.correction',
    # go/keep-sorted end
])

"""Ops that are registered in C++ but don't need to be as pytorch automatically
delegates them to other ops. Each op should be commented with why it needs to be
registered.

This list contains ops that have registered C++ kernels, but for which we don't
require a C++ registration, either because they are not defined, or because
the logic in native_functions_test.py that determines which ops need a C++
registration has filtered them out.
"""
REGISTRATION_OVERRIDES = frozenset([
    # go/keep-sorted start
    # "aten ops rms_norm and scaled_dot_product_attention delegate to
    # _fused_rms_norm and _scaled_dot_product_fused_attention_overrideable.
    # We register these fused ops for more efficient lowerings, rather than
    # overriding the entire delegation behavior".
    '_fused_rms_norm',
    '_grouped_mm',
    '_scaled_dot_product_fused_attention_overrideable',
    '_scaled_dot_product_fused_attention_overrideable_backward',
    '_to_copy',
    'convolution',
    'convolution.out',
    'convolution_backward',
    # copy_ is registered in copy_from_aten_kernels.cc to avoid an infinite
    # recursion when the input is a complex number with the conjugate bit set.
    # The loop is copy_ -> MathOpFallback::fallback_impl -> clone -> copy_...
    # Registering copy_ as an alias for _copy_from breaks this loop.
    'copy_',
    # TODO: b/513607161 - revert once upstream PyTorch bug is fixed.
    # ctc_loss and ctc_loss.Tensor are registered because we provide a custom
    # StableHLO lowering and autograd implementation, bypassing the default
    # decomposition in order to workaround a bug in PyTorch core.
    'ctc_loss',
    'ctc_loss.Tensor',
    'gather',
    # Gelu is registered to handle type promotion for integer and boolean
    # inputs to match PyTorch GPU behavior for functional calls.
    'gelu',
    'native_layer_norm',  # pending removal
    # repeat_interleave.self_Tensor is registered to provide an optimized TPU
    # implementation, overriding the default decomposition.
    'repeat_interleave.self_Tensor',
    # split_with_sizes_copy.out is used by PyTorch's FSDP2 wrapper. The default
    # decomposition performs 2-d reshapes that are inefficient on TPU.
    'split_with_sizes_copy.out',
    # go/keep-sorted end
])

"""Regex version of REGISTRATION_OVERRIDES. The regex is matched against the
registered ops.
"""
REGISTRATION_OVERRIDES_REGEX = frozenset([
    # go/keep-sorted start
    '_foreach_.*',
    # go/keep-sorted end
])
