# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load(
    "//build_files:build_defs.bzl",
    "torch_tpu_package_end",
    "torch_tpu_py_library",
    "torch_tpu_py_test",
)

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//:__subpackages__"],
)

torch_tpu_py_library(
    name = "optimizers",
    srcs = ["optimizers.py"],
    deps = [
        "//shims/torch:pytorch",
    ],
)

torch_tpu_py_test(
    name = "optimizers_test",
    srcs = ["optimizers_test.py"],
    main = "optimizers_test.py",
    tags = [
        "requires-accel-hbm",
        "requires-net:external",
        "requires-tpu-v5lite",
    ],
    deps = [
        ":optimizers",
        "//shims/absl_py/testing:absltest",
        "//shims/absl_py/testing:parameterized",
        "//shims/torch:pytorch",
        "//src/torch_tpu",
        "//src/torch_tpu/_internal/benchmarks:xprof_adapter",
        "//src/torch_tpu/_internal/compile:compiler",
        "//src/torch_tpu/_internal/utils:test_utils",
        "//tests:seed_test_utils",
    ],
)

torch_tpu_py_library(
    name = "single_trace_trainer",
    srcs = ["single_trace_trainer.py"],
    deps = [
        ":optimizers",
        "//shims/torch:pytorch",
    ],
)

torch_tpu_py_test(
    name = "single_trace_trainer_test",
    srcs = ["single_trace_trainer_test.py"],
    main = "single_trace_trainer_test.py",
    nopresubmit = "slow example",
    notest_oss = "slow example",
    tags = [
        "requires-accel-hbm",
        "requires-net:external",
        "requires-tpu-v5lite",
    ],
    deps = [
        ":optimizers",
        ":single_trace_trainer",
        "//shims/absl_py/testing:absltest",
        "//shims/torch:pytorch",
        "//src/torch_tpu",
        "//tests:seed_test_utils",
    ],
)

torch_tpu_package_end()
