# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@xla//third_party/py/rules_pywrap:pywrap.default.bzl", "pybind_extension")
load("//build_files:build_defs.bzl", "define_cpp_filegroup", "torch_tpu_cc_library")
load("//shims/py_rules:pytype.bzl", "pytype_strict_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = [
        "//:__subpackages__",
    ],
)

pytype_strict_library(
    name = "tpu_topology",
    srcs = ["tpu_topology.py"],
)

pytype_strict_library(
    name = "tpu_env",
    srcs = ["tpu_env.py"],
    deps = [
        ":tpu_distributed",
        ":tpu_topology",
        "//shims/absl_py/logging",
        "//shims/torch:pytorch",
        "//torch_tpu/api",
        "@pypi//portpicker",
    ],
)

pytype_strict_library(
    name = "gpu_env",
    srcs = ["gpu_env.py"],
    deps = [
        "//shims/absl_py/logging",
        "//shims/torch:pytorch",
    ],
)

# This library is not used directly, but is needed for go/cclean. Without
# this rule, cclean complains that tpu_distributed.cc has no rule depending on it.
torch_tpu_cc_library(
    name = "tpu_distributed_lib",
    srcs = ["tpu_distributed.cc"],
    deps = [
        "//shims/torch:torch_headers",
        "//shims/torch/c10/util:base_headers",
        "//torch_tpu/common:error_utils",
        "//torch_tpu/distributed:process_group_tpu",
        "//torch_tpu/eager:device",
        "//torch_tpu/pjrt:pjrt_init",
        "@com_google_absl//absl/log:absl_check",
        "@com_google_absl//absl/log:check",
    ],
)

# Ensures that :tpu_distributed_lib builds. Without this, TAP
# won't build it as there's no test depending on it.
build_test(
    name = "tpu_distributed_lib_build_test",
    tags = [
        "oss_ready_cpu",
    ],
    targets = [":tpu_distributed_lib"],
)

pybind_extension(
    name = "tpu_distributed",
    srcs = ["tpu_distributed.cc"],
    common_lib_packages = [
        "torch_tpu/common",
    ],
    wrap_py_init = True,
    deps = [
        "//shims/torch:torch_headers",
        "//shims/torch/c10/util:base_headers",
        "//torch_tpu/common:error_utils",
        "//torch_tpu/distributed:process_group_tpu",
        "//torch_tpu/eager:device",
        "//torch_tpu/pjrt:pjrt_init",
        "@com_google_absl//absl/log:absl_check",
        "@com_google_absl//absl/log:check",
    ],
)

define_cpp_filegroup(name = "all_cpp_files_recursive")
