# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Utilities for SPMD execution in torch_tpu."""

from collections.abc import Callable
import functools
from typing import Any, TypeVar

import torch
from torch.utils import _pytree
from torch_tpu._internal.distributed import tpu_distributed
from torch_tpu._internal.sync import sync

_F = TypeVar("_F", bound=Callable[..., Any])


def spmd_safe(func: _F) -> _F:
  """Decorator that allows users to mark a function as SPMD safe.

  This decorator calls `sync.synchronize(wait=False)` on all input and output
  tensors of the function which ensures no outside operations can get fused into
  the execution graphs generated by the function.
  The decorator marks entry and exit of a SPMD safe region which enables
  enabling fat collectives for the graph generated by the function.


  Args:
    func: The function to decorate.

  Returns:
    The decorated function.

  Example:
    @spmd_safe
    def my_func(x: torch.Tensor) -> torch.Tensor:
      y = x * 5
      dist.all_reduce(y)
      return y
  """

  @functools.wraps(func)
  def wrapper(*args: Any, **kwargs: Any) -> Any:
    # Synchronize all input tensors.
    flat_args, _ = _pytree.tree_flatten((args, kwargs))
    input_tensors = [
        t
        for t in flat_args
        if isinstance(t, torch.Tensor) and t.device != torch.device("cpu")
    ]
    if input_tensors:
      sync.synchronize(input_tensors, wait=False)

    tpu_distributed.enter_spmd_safe_region()
    try:
      result = func(*args, **kwargs)
    finally:
      tpu_distributed.exit_spmd_safe_region()

    # Synchronize all output tensors.
    flat_result, _ = _pytree.tree_flatten(result)
    output_tensors = [
        t
        for t in flat_result
        if isinstance(t, torch.Tensor) and t.device != torch.device("cpu")
    ]
    if output_tensors:
      sync.synchronize(output_tensors, wait=False)

    return result

  return wrapper  # pytype: disable=bad-return-type
