# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for the device module with TPU backend."""

from absl.testing import absltest
import torch
from tests.device import device_module_testing


# Test cases are defined in device_module_testing.DeviceModuleBase
class TpuDeviceModuleTest(
    device_module_testing.DeviceModuleBase, absltest.TestCase
):

  @property
  def device_module(self):
    return torch.tpu

  # ------------------------------------------------------------------
  # PrivateUse1 backend attrs generated by
  # torch.utils.generate_methods_for_privateuse1_backend() in _loader.py.
  # These attrs are absent unless _loader.py calls generate_methods_*; they
  # are what lets user code use idioms like `if t.is_tpu` and `model.tpu()`.
  # ------------------------------------------------------------------

  def test_tensor_is_tpu_attr(self):
    t = torch.zeros(1, device="tpu")
    self.assertTrue(hasattr(t, "is_tpu"))
    self.assertTrue(t.is_tpu)
    self.assertFalse(torch.zeros(1).is_tpu)

  def test_tensor_tpu_method(self):
    t = torch.zeros(1).tpu()
    self.assertEqual(t.device.type, "tpu")

  def test_module_tpu_method(self):
    m = torch.nn.Linear(1, 1).tpu()
    self.assertEqual(next(m.parameters()).device.type, "tpu")


if __name__ == "__main__":
  absltest.main()
