# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for the device module with TPU backend."""

from absl.testing import absltest
import torch
from torch._dynamo.device_interface import get_interface_for_device
from tests.device import device_module_testing


# Test cases are defined in device_module_testing.DeviceModuleBase
class TpuDeviceModuleTest(
    device_module_testing.DeviceModuleBase,
    absltest.TestCase,  # ABSLTEST_OK=Reference to absltest.TestCase
):

  @property
  def device_module(self):
    return torch.tpu

  # ------------------------------------------------------------------
  # PrivateUse1 backend attrs generated by
  # torch.utils.generate_methods_for_privateuse1_backend() in _loader.py.
  # These attrs are absent unless _loader.py calls generate_methods_*; they
  # are what lets user code use idioms like `if t.is_tpu` and `model.tpu()`.
  # ------------------------------------------------------------------

  def test_tensor_is_tpu_attr(self):
    t = torch.zeros(1, device="tpu")
    self.assertTrue(hasattr(t, "is_tpu"))
    self.assertTrue(t.is_tpu)
    self.assertFalse(torch.zeros(1).is_tpu)

  def test_tensor_tpu_method(self):
    t = torch.zeros(1).tpu()
    self.assertEqual(t.device.type, "tpu")

  def test_module_tpu_method(self):
    m = torch.nn.Linear(1, 1).tpu()
    self.assertEqual(next(m.parameters()).device.type, "tpu")

  def test_device_interface_registration_always_wins(self):
    """Verifies device_module from _loader.py is registered as device interface."""
    iface = get_interface_for_device("tpu")
    self.assertEqual(iface, self.device_module)

  def test_get_device_properties_multi_processor_count(self):
    props = self.device_module.get_device_properties()
    self.assertTrue(hasattr(props, "multi_processor_count"))
    self.assertIsInstance(props.multi_processor_count, int)
    self.assertGreaterEqual(props.multi_processor_count, 1)

    iface_props = get_interface_for_device("tpu").get_device_properties("tpu")
    self.assertTrue(hasattr(iface_props, "multi_processor_count"))
    self.assertIsInstance(iface_props.multi_processor_count, int)
    self.assertGreaterEqual(iface_props.multi_processor_count, 1)

  def test_get_multi_processor_count(self):
    self.assertEqual(self.device_module.get_multi_processor_count(), 1)
    self.assertEqual(self.device_module.get_multi_processor_count("tpu"), 1)

    iface = get_interface_for_device("tpu")
    self.assertEqual(iface.get_multi_processor_count("tpu"), 1)
    self.assertEqual(iface.get_multi_processor_count(), 1)

  def test_get_compute_capability(self):
    capability = self.device_module.get_compute_capability()
    self.assertIsInstance(capability, str)

    iface_cap = get_interface_for_device("tpu").get_compute_capability("tpu")
    self.assertIsInstance(iface_cap, str)

  def test_is_triton_capable(self):
    self.assertFalse(torch.tpu.is_triton_capable())
    self.assertFalse(torch.tpu.is_triton_capable(device=None))

  def test_is_gpu(self):
    self.assertFalse(torch.tpu.is_gpu())

  def test_window_num_stripes(self):
    """Tests torch.tpu.window_num_stripes property."""
    original = torch.tpu.window_num_stripes
    try:
      self.assertEqual(original, 4)
      torch.tpu.window_num_stripes = 8
      self.assertEqual(torch.tpu.window_num_stripes, 8)
    finally:
      torch.tpu.window_num_stripes = original

  def test_window_stripe_chunk_mb(self):
    """Tests torch.tpu.window_stripe_chunk_mb property."""
    original = torch.tpu.window_stripe_chunk_mb
    try:
      self.assertEqual(original, 8)
      torch.tpu.window_stripe_chunk_mb = 16
      self.assertEqual(torch.tpu.window_stripe_chunk_mb, 16)
    finally:
      torch.tpu.window_stripe_chunk_mb = original

  def test_compute_window_stripe_count(self):
    """Tests stripe count calculation logic across tensor byte sizes and configurations."""
    from torch_tpu._internal.device import _device_ops_backend

    compute_fn = getattr(
        _device_ops_backend, "_compute_window_stripe_count", None
    )
    if compute_fn is None:
      return

    original_stripes = torch.tpu.window_num_stripes
    original_chunk_mb = torch.tpu.window_stripe_chunk_mb
    try:
      # Default: 8 MB chunk, 4 max stripes
      torch.tpu.window_num_stripes = 4
      torch.tpu.window_stripe_chunk_mb = 8
      mb = 1024 * 1024

      self.assertEqual(compute_fn(0), 1)
      self.assertEqual(compute_fn(1024), 1)
      self.assertEqual(compute_fn(7 * mb), 1)
      self.assertEqual(compute_fn(8 * mb), 1)
      self.assertEqual(compute_fn(15 * mb), 1)
      self.assertEqual(compute_fn(16 * mb), 2)
      self.assertEqual(compute_fn(23 * mb), 2)
      self.assertEqual(compute_fn(24 * mb), 3)
      self.assertEqual(compute_fn(31 * mb), 3)
      self.assertEqual(compute_fn(32 * mb), 4)
      self.assertEqual(compute_fn(64 * mb), 4)
      self.assertEqual(compute_fn(128 * mb), 4)

      # Custom: 4 MB chunk, 8 max stripes
      torch.tpu.window_num_stripes = 8
      torch.tpu.window_stripe_chunk_mb = 4

      self.assertEqual(compute_fn(4 * mb), 1)
      self.assertEqual(compute_fn(8 * mb), 2)
      self.assertEqual(compute_fn(16 * mb), 4)
      self.assertEqual(compute_fn(32 * mb), 8)
      self.assertEqual(compute_fn(64 * mb), 8)
    finally:
      torch.tpu.window_num_stripes = original_stripes
      torch.tpu.window_stripe_chunk_mb = original_chunk_mb


if __name__ == "__main__":
  absltest.main()
