/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TORCH_TPU_OPS_OP_NAMES_H_
#define TORCH_TPU_OPS_OP_NAMES_H_

#include <ostream>
#include <string_view>

#include "torch_tpu/common/fingerprint_utils.h"

namespace torch_tpu {

// Identifies ops implemented by TorchTPU. The numerical values of the enum
// members are unstable and not meaningful, so do not persist them.
enum class OpName {
  kMinOpMinus1,  // For enumerating all OpNames for testing. Not a real op.
  // go/keep-sorted start
  kAbsOut,
  kAcosOut,
  kAcoshOut,
  kAdaptiveAvgPool2d,
  kAdaptiveAvgPool2dBackward,
  kAdaptiveAvgPool2dOut,
  kAdaptiveAvgPool3d,
  kAdaptiveAvgPool3dBackward,
  kAdaptiveAvgPool3dBackwardGradInput,
  kAdaptiveAvgPool3dOut,
  kAdd,
  kAddOut,
  kAddReluOut,
  kAddReluScalar,
  kAddReluTensor,
  kAddRelu_Scalar,
  kAddRelu_Tensor,
  kAddcdivOut,
  kAddcmulOut,
  kAddmm,
  kAddmmDtype,
  kAddmmDtypeOut,
  kAddmmOut,
  kAddmvOut,
  kAlias,
  kAllAllOut,
  kAllOut,
  kAmax,
  kAmaxOut,
  kAmin,
  kAminOut,
  kAminmaxOut,
  kAnyAllOut,
  kAnyOut,
  kArangeStartOut,
  kArgMaxOut,
  kArgMinOut,
  kAsStrided,
  kAsStridedInverse,
  kAsinOut,
  kAsinhOut,
  kAssertAsync,
  kAssertAsyncMsg,
  kAtan2Out,
  kAtanOut,
  kAtanhOut,
  kAvgPool2dBackwardGradInput,
  kAvgPool2dOut,
  kAvgPool3dBackwardGradInput,
  kAvgPool3dOut,
  kBaddbmmDtype,
  kBaddbmmDtypeOut,
  kBaddbmmOut,
  kBernoulliOut,
  kBernoulli_Float,
  kBernoulli_Tensor,
  kBinCount,
  kBitwiseAnd,
  kBitwiseAndOut,
  kBitwiseAndTensorOut,
  kBitwiseLeftShiftTensorOut,
  kBitwiseNotOut,
  kBitwiseOr,
  kBitwiseOrOut,
  kBitwiseOrTensorOut,
  kBitwiseRightShiftTensorOut,
  kBitwiseXor,
  kBitwiseXorOut,
  kBitwiseXorTensorOut,
  kBmm,
  kBmmDtype,
  kBmmDtypeOut,
  kBmmOut,
  kBucketizeScalar,
  kBucketizeTensor,
  kBucketizeTensorOut,
  kCatOut,
  kCdistBackward,
  kCdistForward,
  kCeilOut,
  kClampMaxOut,
  kClampMaxTensorOut,
  kClampMinOut,
  kClampMinTensorOut,
  kClampOut,
  kClampTensorOut,
  kCol2Im,
  kCol2ImOut,
  kCompileMlir,
  kComplexOut,
  kConjPhysicalOut,
  kConstantPadNd,
  kConvolution,
  kConvolutionBackward,
  kConvolutionOut,
  kCopyFrom,
  kCopyFromAndResize,
  kCopy_,
  kCosOut,
  kCoshOut,
  kCountNonzeroDimIntList,
  kCtcLoss,
  kCtcLossBackward,
  kCtcLossBackwardTensor,
  kCtcLossPublic,
  kCtcLossPublicTensor,
  kCtcLossTensor,
  kCummaxHelper,
  kCumminHelper,
  kCumprodOut,
  kCumsumOut,
  kCustomKernel,
  kDetach,
  kDetach_,
  kDigammaOut,
  kDistributedAllGather,
  kDistributedAllGatherIntoTensor,
  kDistributedAllReduce,
  kDistributedAllToAll,
  kDistributedAllToAllSingle,
  kDistributedBarrier,
  kDistributedBroadcast,
  kDistributedExperimentalRecv,
  kDistributedExperimentalSend,
  kDistributedGather,
  kDistributedReduceScatter,
  kDistributedReduceScatterTensor,
  kDistributedReduceScatterTensorCoalesced,
  kDistributedScatter,
  kDiv,
  kDivOut,
  kDivOutMode,
  kDot,
  kDropout,
  kDynamicArange,
  kDynamicBroadcast,
  kDynamicReshape,
  kEfficientZeroTensor,
  kEluBackwardGradInput,
  kEluOut,
  kEmbeddingBag,
  kEmbeddingBagBackward,
  kEmbeddingBagForwardOnly,
  kEmbeddingDenseBackward,
  kEmbeddingRenorm_,
  kEmpty,
  kEmptyMemoryFormat,
  kEmptyStrided,
  kEq,
  kEqOut,
  kEqScalarOut,
  kEqTensorOut,
  kEqual,
  kErfInvOut,
  kErfOut,
  kExp2Out,
  kExpM1Out,
  kExpOut,
  kExponential_,
  kEyeMOut,
  kEyeOut,
  kFakeQuantizePerTensorAffineCachemask,
  kFftC2c,
  kFftC2cOut,
  kFftC2r,
  kFftC2rOut,
  kFftR2c,
  kFftR2cOut,
  kFill_Scalar,
  kFill_Tensor,
  kFlatten,
  kFlip,
  kFloorDivide,
  kFloorDivideOut,
  kFloorDivide_,
  kFloorDivide_Tensor,
  kFloorOut,
  kFmaxOut,
  kFminOut,
  kFmodTensorOut,
  kForceStrides,
  kForeachAbs,
  kForeachAbsCommon,
  kForeachAbs_,
  kForeachAcos,
  kForeachAcos_,
  kForeachAddCommon,
  kForeachAddList,
  kForeachAddScalar,
  kForeachAddScalarList,
  kForeachAddTensor,
  kForeachAdd_List,
  kForeachAdd_Scalar,
  kForeachAdd_ScalarList,
  kForeachAdd_Tensor,
  kForeachAddcdivScalar,
  kForeachAddcdivScalarList,
  kForeachAddcdivTensor,
  kForeachAddcdiv_Scalar,
  kForeachAddcdiv_ScalarList,
  kForeachAddcdiv_Tensor,
  kForeachAddcmulScalar,
  kForeachAddcmulScalarList,
  kForeachAddcmulTensor,
  kForeachAddcmul_Scalar,
  kForeachAddcmul_ScalarList,
  kForeachAddcmul_Tensor,
  kForeachAsin,
  kForeachAsin_,
  kForeachAtan,
  kForeachAtan_,
  kForeachCeil,
  kForeachCeil_,
  kForeachClampMaxList,
  kForeachClampMaxScalar,
  kForeachClampMaxScalarList,
  kForeachClampMax_List,
  kForeachClampMax_Scalar,
  kForeachClampMax_ScalarList,
  kForeachClampMinList,
  kForeachClampMinScalar,
  kForeachClampMinScalarList,
  kForeachClampMin_List,
  kForeachClampMin_Scalar,
  kForeachClampMin_ScalarList,
  kForeachCopy_,
  kForeachCos,
  kForeachCos_,
  kForeachCosh,
  kForeachCosh_,
  kForeachDivCommon,
  kForeachDivList,
  kForeachDivScalar,
  kForeachDivScalarList,
  kForeachDivTensor,
  kForeachDiv_List,
  kForeachDiv_Scalar,
  kForeachDiv_ScalarList,
  kForeachDiv_Tensor,
  kForeachErf,
  kForeachErf_,
  kForeachErfc,
  kForeachErfc_,
  kForeachExp,
  kForeachExp_,
  kForeachExpm1,
  kForeachExpm1_,
  kForeachFloor,
  kForeachFloor_,
  kForeachFrac,
  kForeachFrac_,
  kForeachLerpCommon,
  kForeachLerpList,
  kForeachLerpScalar,
  kForeachLerpScalarList,
  kForeachLerp_List,
  kForeachLerp_Scalar,
  kForeachLerp_ScalarList,
  kForeachLgamma,
  kForeachLgamma_,
  kForeachLog,
  kForeachLog10,
  kForeachLog10_,
  kForeachLog1p,
  kForeachLog1p_,
  kForeachLog2,
  kForeachLog2_,
  kForeachLog_,
  kForeachMax,
  kForeachMaximumList,
  kForeachMaximumScalar,
  kForeachMaximumScalarList,
  kForeachMaximum_List,
  kForeachMaximum_Scalar,
  kForeachMaximum_ScalarList,
  kForeachMinimumList,
  kForeachMinimumScalar,
  kForeachMinimumScalarList,
  kForeachMinimum_List,
  kForeachMinimum_Scalar,
  kForeachMinimum_ScalarList,
  kForeachMulCommon,
  kForeachMulList,
  kForeachMulScalar,
  kForeachMulScalarList,
  kForeachMulTensor,
  kForeachMul_List,
  kForeachMul_Scalar,
  kForeachMul_ScalarList,
  kForeachMul_Tensor,
  kForeachNeg,
  kForeachNeg_,
  kForeachNormScalar,
  kForeachPowList,
  kForeachPowScalar,
  kForeachPowScalarAndTensor,
  kForeachPowScalarList,
  kForeachPow_List,
  kForeachPow_Scalar,
  kForeachPow_ScalarList,
  kForeachReciprocal,
  kForeachReciprocal_,
  kForeachRound,
  kForeachRoundCommon,
  kForeachRound_,
  kForeachRsqrt,
  kForeachRsqrt_,
  kForeachSigmoid,
  kForeachSigmoid_,
  kForeachSign,
  kForeachSign_,
  kForeachSin,
  kForeachSin_,
  kForeachSinh,
  kForeachSinh_,
  kForeachSqrt,
  kForeachSqrt_,
  kForeachSubList,
  kForeachSubScalar,
  kForeachSubScalarList,
  kForeachSub_List,
  kForeachSub_Scalar,
  kForeachSub_ScalarList,
  kForeachTan,
  kForeachTan_,
  kForeachTanh,
  kForeachTanh_,
  kForeachTrunc,
  kForeachTrunc_,
  kForeachZero_,
  kFusedRmsNorm,
  kFusedRmsNormBackward,
  kFusedSdpChoice,
  kGather,
  kGatherOut,
  kGe,
  kGeOut,
  kGeScalarOut,
  kGeTensorOut,
  kGelu,
  kGeluBackwardGradInput,
  kGeluOut,
  kGeqrf,
  kGeqrfA,
  kGetDimensionSize,
  kGluBackward,
  kGluBackwardGradInput,
  kGluOut,
  kGridSampler2d,
  kGridSampler2dBackward,
  kGridSampler3d,
  kGridSampler3dBackward,
  kGroupedMm,
  kGt,
  kGtOut,
  kGtScalarOut,
  kGtTensorOut,
  kHardsigmoidBackwardGradInput,
  kHardsigmoidOut,
  kHardswish,
  kHardswishBackward,
  kHardswishOut,
  kHardswish_,
  kHardtanh,
  kHardtanhBackward,
  kHardtanhBackwardGradInput,
  kHardtanhOut,
  kHardtanh_,
  kHistc,
  kHistcOut,
  kIlshiftScalar,
  kIlshiftTensor,
  kIm2Col,
  kIm2ColOut,
  kIndexAdd,
  kIndexAddOut,
  kIndexCopyOut,
  kIndexFillIntScalar,
  kIndexFillIntTensor,
  kIndexPutImpl_,
  kIndexReduceOut,
  kIndexSelect,
  kIndexTensorOut,
  kIrshiftScalar,
  kIrshiftTensor,
  kIsInScalarTensorOut,
  kIsInTensorScalarOut,
  kIsInTensorTensorOut,
  kIsNan,
  kIsNegInfOut,
  kIsPosInfOut,
  kLayerNorm,
  kLdexpOut,
  kLdexpTensor,
  kLdexp_,
  kLe,
  kLeOut,
  kLeScalarOut,
  kLeTensorOut,
  kLeakyReluBackward,
  kLeakyReluOut,
  kLerpScalarOut,
  kLerpTensorOut,
  kLgammaOut,
  kLiftFreshOut,
  kLinalgInvExInverse,
  kLinalgLuFactorExOut,
  kLinalgLuOut,
  kLinalgLuSolveOut,
  kLinalgQrOut,
  kLinalgSolveExOut,
  kLinalgSolveTriangular,
  kLinalgSolveTriangularOut,
  kLinalgVectorNormOut,
  kLinspaceOut,
  kLocalScalarDense,
  kLog10Out,
  kLog1pOut,
  kLog2Out,
  kLogOut,
  kLogSigmoidBackward,
  kLogSigmoidBackwardGradInput,
  kLogSigmoidForward,
  kLogSigmoidForwardOut,
  kLogSoftmaxBackwardDataOut,
  kLogSoftmaxOut,
  kLogcumsumexp,
  kLogcumsumexpOut,
  kLogicalAndOut,
  kLogicalNotOut,
  kLogicalOrOut,
  kLogicalXorOut,
  kLshiftScalar,
  kLshiftTensor,
  kLt,
  kLtOut,
  kLtScalarOut,
  kLtTensorOut,
  kLuUnpackOut,
  kMaskedFill_Scalar,
  kMaskedFill_Tensor,
  kMaskedScatter_,
  kMaskedSelect,
  kMaskedSelectOut,
  kMaskedSelectSize,
  kMax,
  kMaxDimMax,
  kMaxPool2d,
  kMaxPool2dBackward,
  kMaxPool2dWithIndicesBackwardGradInput,
  kMaxPool2dWithIndicesOut,
  kMaxPool3dWithIndices,
  kMaxPool3dWithIndicesBackward,
  kMaxPool3dWithIndicesBackwardGradInput,
  kMaxPool3dWithIndicesOut,
  kMaxUnaryOut,
  kMaximum,
  kMaximumOut,
  kMeanOut,
  kMin,
  kMinDimMin,
  kMinUnaryOut,
  kMinimum,
  kMinimumOut,
  kMmDtype,
  kMmDtypeOut,
  kMmOut,
  kMseLossBackward,
  kMseLossOut,
  kMul,
  kMulOut,
  kMultinomial,
  kMultinomialOut,
  kNanToNumOut,
  kNativeBatchNorm,
  kNativeBatchNormBackward,
  kNativeBatchNormLegit,
  kNativeBatchNormLegitNoStats,
  kNativeBatchNormLegitNoStatsOut,
  kNativeBatchNormLegitOut,
  kNativeBatchNormOut,
  kNativeDropout,
  kNativeDropoutBackward,
  kNativeGroupNormBackward,
  kNativeLayerNorm,
  kNativeLayerNormBackward,
  kNe,
  kNeOut,
  kNeScalarOut,
  kNeTensorOut,
  kNegOut,
  kNllLoss2dBackward,
  kNllLoss2dBackwardGradInput,
  kNllLoss2dForward,
  kNllLoss2dForwardOut,
  kNllLossBackwardGradInput,
  kNllLossForwardOut,
  kNonzero,
  kNonzeroOut,
  kNonzeroSize,
  kNormalFloatTensor,
  kNormalFloatTensorOut,
  kNormalTensorFloat,
  kNormalTensorFloatOut,
  kNormalTensorTensor,
  kNormalTensorTensorOut,
  kNormal_,
  kPadUninitialized_,
  kPdistBackward,
  kPdistForward,
  kPolarOut,
  kPolygammaOut,
  kPow,
  kPowOut,
  kPowScalarOut,
  kPowTensorScalarOut,
  kPowTensorTensorOut,
  kProd,
  kProdDimOut,
  kPut_,
  kRaggedAllToAll,
  kRaggedAllToAllOut,
  kRaggedDot,
  kRaggedDotOut,
  kRandom_,
  kRandom_From,
  kRandom_To,
  kRandpermGeneratorOut,
  kReciprocalOut,
  kReflectionPad1dBackwardGradInput,
  kReflectionPad1dOut,
  kReflectionPad2d,
  kReflectionPad2dBackward,
  kReflectionPad2dBackwardGradInput,
  kReflectionPad2dOut,
  kReflectionPad3dBackwardGradInput,
  kReflectionPad3dOut,
  kRelu,
  kRelu_,
  kRemainder,
  kRemainderOut,
  kRemainderScalarTensor,
  kRemainderTensorOut,
  kRepeat,
  kRepeatInterleaveSelfTensor,
  kReplicationPad1dBackwardGradInput,
  kReplicationPad1dOut,
  kReplicationPad2dBackward,
  kReplicationPad2dBackwardGradInput,
  kReplicationPad2dOut,
  kReplicationPad3dBackward,
  kReplicationPad3dBackwardGradInput,
  kReplicationPad3dOut,
  kReshapeAlias,
  kResize_,
  kResolveNegativeIndices,
  kRmsNorm,
  kRngSeed,
  kRngSetOffset,
  kRngSetSeed,
  kRngSetStateComponent,
  kRngStateUpdate,
  kRoll,
  kRound,
  kRoundDecimalsOut,
  kRoundOut,
  kRshiftScalar,
  kRshiftTensor,
  kRsqrtOut,
  kRsub,
  kRsubTensor,
  kScalarTensor,
  kScaledDotProductEfficientAttention,
  kScaledDotProductFlashAttention,
  kScaledDotProductFlashAttentionBackward,
  kScaledDotProductFusedAttentionOverrideable,
  kScaledDotProductFusedAttentionOverrideableBackward,
  kScaledMm,
  kScaledMmOut,
  kScatterAddOut,
  kScatterReduceOut,
  kScatterReduceTwoOut,
  kScatterSrcOut,
  kScatterValueOut,
  kScatterValueReduceOut,
  kSetDimensionLogicalSize,
  kSet_,
  kSet_SourceStorage,
  kSet_SourceStorageOffset,
  kSet_SourceTensor,
  kSgnOut,
  kSigmoidBackwardGradInput,
  kSigmoidOut,
  kSignOut,
  kSignbitOut,
  kSiluOut,
  kSinOut,
  kSinhOut,
  kSlice,
  kSoftmaxBackwardDataOut,
  kSoftmaxOut,
  kSoftplusBackwardGradInput,
  kSoftplusOut,
  kSortValuesStable,
  kSparseDenseMatmul,
  kSparseDenseMatmulGradWithAdagrad,
  kSparseDenseMatmulGradWithSgd,
  kSplitWithSizesCopyOut,
  kSqrtOut,
  kSub,
  kSubOut,
  kSum,
  kSumIntListOut,
  kTake,
  kTakeOut,
  kTanOut,
  kTanhBackwardGradInput,
  kTanhOut,
  kThresholdBackwardGradInput,
  kThresholdOut,
  kTo,
  kToCopy,
  kTopkValues,
  kTorchTpuInternalConstant,
  kTorchTpuInternalGatherAllSubgroups,
  kTorchTpuInternalZeroSize,
  kTorchTpuOptimizationBarrier,
  kTorchTpuStorageAllocate,
  kTrilIndices,
  kTrilOut,
  kTriuOut,
  kTruncOut,
  kUnfold,
  kUnfoldBackward,
  kUniform_,
  kUnique2,
  kUnsqueeze,
  kUnsqueezeCopy,
  kUnsqueezeCopyOut,
  kUnsqueeze_,
  kUntypedStorageResize_,
  kUpsampleBicubic2dBackwardGradInput,
  kUpsampleBicubic2dOut,
  kUpsampleBilinear2dBackwardGradInput,
  kUpsampleBilinear2dOut,
  kUpsampleNearest1dBackwardGradInput,
  kUpsampleNearest1dOut,
  kUpsampleNearest2dBackwardGradInput,
  kUpsampleNearest2dOut,
  kUpsampleNearest3dBackwardGradInput,
  kUpsampleNearest3dOut,
  kUpsampleNearestExact1dBackwardGradInput,
  kUpsampleNearestExact1dOut,
  kUpsampleNearestExact2dBackwardGradInput,
  kUpsampleNearestExact2dOut,
  kUpsampleNearestExact3dBackwardGradInput,
  kUpsampleNearestExact3dOut,
  kVar,
  kVarCorrection,
  kVarCorrectionOut,
  kVarOut,
  kVdot,
  kView,
  kViewAsComplex,
  kViewAsReal,
  kWeightNormInterface,
  kWhereSelf,
  kWhereSelfOut,
  kXlogyOutTensor,
  kZero_,
  // go/keep-sorted end
  kMaxOpPlus1,  // For enumerating all OpNames for testing. Not a real op.
};

// Formats an op name as a human-readable string.
[[nodiscard]] std::string_view ToString(OpName op_name);
template <typename Sink>
void AbslStringify(Sink& sink, OpName op_name) {
  sink.Append(ToString(op_name));
}
inline std::ostream& operator<<(std::ostream& os, const OpName op_name) {
  return os << ToString(op_name);
}

// Returns the base name of the op, i.e. as it would appear in user PyTorch
// code. For example, both kAdd and kAddOut -> "add" as a user doesn't write
// "add.out(...)" in their code. This should be used for error reporting.
[[nodiscard]] std::string_view ToBaseName(OpName op_name);

// Returns true if the op is a distributed op.
[[nodiscard]] inline bool IsDistributedOp(OpName op_name) {
  switch (op_name) {
    case OpName::kDistributedAllGather:
    case OpName::kDistributedAllGatherIntoTensor:
    case OpName::kDistributedAllReduce:
    case OpName::kDistributedAllToAll:
    case OpName::kDistributedAllToAllSingle:
    case OpName::kDistributedBarrier:
    case OpName::kDistributedBroadcast:
    case OpName::kDistributedExperimentalRecv:
    case OpName::kDistributedExperimentalSend:
    case OpName::kDistributedGather:
    case OpName::kDistributedReduceScatter:
    case OpName::kDistributedReduceScatterTensor:
    case OpName::kDistributedReduceScatterTensorCoalesced:
    case OpName::kDistributedScatter:
      return true;
    default:
      return false;
  }
}

// Returns true if the op is a side-effecting op.
[[nodiscard]] inline bool IsSideEffectingOp(OpName op_name) {
  return IsDistributedOp(op_name);
}

// Returns true if the op is an "empty" op, i.e. one that creates a tensor
// with uninitialized data.
[[nodiscard]] inline bool IsEmptyOp(OpName op_name) {
  switch (op_name) {
    case OpName::kEmpty:
    case OpName::kEmptyMemoryFormat:
    case OpName::kEmptyStrided:
      return true;
    default:
      return false;
  }
}

// Returns true if the op would would be metadata-only on CUDA.
// When creating these ops, we should usually not need to materialize them,
// even in kDeferNever mode.
[[nodiscard]] inline bool IsMetadataOnly(OpName op_name) {
  switch (op_name) {
    case OpName::kAlias:
    case OpName::kAsStrided:
    case OpName::kAsStridedInverse:
    case OpName::kReshapeAlias:
    case OpName::kUnsqueeze:
    case OpName::kUnsqueezeCopy:
    case OpName::kUnsqueezeCopyOut:
    case OpName::kUnsqueeze_:
    case OpName::kView:
    case OpName::kViewAsComplex:
    case OpName::kViewAsReal:
      // On CUDA, view operations are not separate kernels, they're just read
      // patterns from a provided CUDA buffer.
      // Similarly, writes to buffers are just pointer dereferences.
      return true;
    case OpName::kDetach:
    case OpName::kDetach_:
      // Detach removes the grad tensor on the CPU, but doesn't have any
      // associated compute.
      return true;
    case OpName::kEmpty:
    case OpName::kEmptyMemoryFormat:
    case OpName::kEmptyStrided:
      // "Empty" ops on CUDA are allocation events, which don't have any
      // associated compute.
      return true;
    case OpName::kTorchTpuInternalConstant:
      // Constant ops are compiled-mode only.
      return true;
    case OpName::kTorchTpuInternalZeroSize:
      // Zero-size ops don't need to be early-materialized as they have nothing
      // to compute.
      return true;
    case OpName::kResize_:
      // Resize_ behaves either like a view or allocation event, depending on
      // if it is increasing or decreasing the tensor size.
      // Either way, there's no associated compute.
      return true;
    case OpName::kSet_:
    case OpName::kSet_SourceStorage:
    case OpName::kSet_SourceStorageOffset:
    case OpName::kSet_SourceTensor:
      // The "set" ops change the relationship between a Tensor and storage, but
      // don't change the values in that storage.
      return true;
    default:
      return false;
  }
}
namespace internal {

// Specialization for `OpName`.
template <>
struct Fingerprint64Impl<OpName, /*kIsSmallIntegral=*/false> {
  [[nodiscard]] static FingerprintType Compute(const OpName op_name) {
    // The string op names are unique and stable as they are used for
    // registering ops with PyTorch.
    return Fingerprint(ToString(op_name));
  }
};

}  // namespace internal

}  // namespace torch_tpu

#endif  // TORCH_TPU_OPS_OP_NAMES_H_
