/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "torch_tpu/ops/op_names.h"

#include <string_view>

#include "absl/strings/match.h"

namespace torch_tpu {

// NOLINTNEXTLINE(readability/fn_size)
std::string_view ToString(OpName op_name) {
  switch (op_name) {
    // go/keep-sorted start
    case OpName::kAbsOut:
      return "abs.out";
    case OpName::kAcosOut:
      return "acos.out";
    case OpName::kAcoshOut:
      return "acosh.out";
    case OpName::kAdaptiveAvgPool2d:
      return "_adaptive_avg_pool2d";
    case OpName::kAdaptiveAvgPool2dBackward:
      return "_adaptive_avg_pool2d_backward";
    case OpName::kAdaptiveAvgPool2dOut:
      return "adaptive_avg_pool2d.out";
    case OpName::kAdaptiveAvgPool3d:
      return "_adaptive_avg_pool3d";
    case OpName::kAdaptiveAvgPool3dBackward:
      return "_adaptive_avg_pool3d_backward";
    case OpName::kAdaptiveAvgPool3dBackwardGradInput:
      return "adaptive_avg_pool3d_backward.grad_input";
    case OpName::kAdaptiveAvgPool3dOut:
      return "adaptive_avg_pool3d.out";
    case OpName::kAdd:
      return "add";
    case OpName::kAddOut:
      return "add.out";
    case OpName::kAddcdivOut:
      return "addcdiv.out";
    case OpName::kAddcmulOut:
      return "addcmul.out";
    case OpName::kAddmm:
      return "addmm";
    case OpName::kAddmmDtype:
      return "addmm.dtype";
    case OpName::kAddmmDtypeOut:
      return "addmm.dtype_out";
    case OpName::kAddmmOut:
      return "addmm.out";
    case OpName::kAddmvOut:
      return "addmv.out";
    case OpName::kAlias:
      return "alias";
    case OpName::kAllAllOut:
      return "all.all_out";
    case OpName::kAllOut:
      return "all.out";
    case OpName::kAmax:
      return "amax";
    case OpName::kAmin:
      return "amin";
    case OpName::kAminmaxOut:
      return "aminmax.out";
    case OpName::kAnyAllOut:
      return "any.all_out";
    case OpName::kAnyOut:
      return "any.out";
    case OpName::kArangeStartOut:
      return "arange.start_out";
    case OpName::kArgMaxOut:
      return "argmax.out";
    case OpName::kArgMinOut:
      return "argmin.out";
    case OpName::kAsStrided:
      return "as_strided";
    case OpName::kAsStridedInverse:
      return "as_strided_inverse";
    case OpName::kAsinOut:
      return "asin.out";
    case OpName::kAsinhOut:
      return "asinh.out";
    case OpName::kAtan2Out:
      return "atan2.out";
    case OpName::kAtanOut:
      return "atan.out";
    case OpName::kAtanhOut:
      return "atanh.out";
    case OpName::kAvgPool2dBackwardGradInput:
      return "avg_pool2d_backward.grad_input";
    case OpName::kAvgPool2dOut:
      return "avg_pool2d.out";
    case OpName::kAvgPool3dBackwardGradInput:
      return "avg_pool3d_backward.grad_input";
    case OpName::kAvgPool3dOut:
      return "avg_pool3d.out";
    case OpName::kBernoulli_Float:
      return "bernoulli_.float";
    case OpName::kBinCount:
      return "bincount";
    case OpName::kBitwiseAnd:
      return "bitwise_and";
    case OpName::kBitwiseAndOut:
      return "bitwise_and.out";
    case OpName::kBitwiseLeftShiftTensorOut:
      return "bitwise_left_shift.Tensor_out";
    case OpName::kBitwiseOr:
      return "bitwise_or";
    case OpName::kBitwiseOrOut:
      return "bitwise_or.out";
    case OpName::kBitwiseRightShiftTensorOut:
      return "bitwise_right_shift.Tensor_out";
    case OpName::kBitwiseXor:
      return "bitwise_xor";
    case OpName::kBitwiseXorOut:
      return "bitwise_xor.out";
    case OpName::kBmm:
      return "bmm";
    case OpName::kBmmDtypeOut:
      return "bmm.dtype_out";
    case OpName::kBmmOut:
      return "bmm.out";
    case OpName::kCatOut:
      return "cat.out";
    case OpName::kCdistForward:
      return "_cdist_forward";
    case OpName::kCeilOut:
      return "ceil.out";
    case OpName::kClampMaxOut:
      return "clamp_max.out";
    case OpName::kClampMaxTensorOut:
      return "clamp_max.Tensor_out";
    case OpName::kClampMinOut:
      return "clamp_min.out";
    case OpName::kClampMinTensorOut:
      return "clamp_min.Tensor_out";
    case OpName::kClampOut:
      return "clamp.out";
    case OpName::kClampTensorOut:
      return "clamp.Tensor_out";
    case OpName::kCol2Im:
      return "col2im";
    case OpName::kCol2ImOut:
      return "col2im.out";
    case OpName::kCompileMlir:
      return "compile_mlir";
    case OpName::kComplexOut:
      return "complex.out";
    case OpName::kConjPhysicalOut:
      return "conj_physical.out";
    case OpName::kConstantPadNd:
      return "constant_pad_nd";
    case OpName::kConvolution:
      return "convolution";
    case OpName::kConvolutionBackward:
      return "convolution_backward";
    case OpName::kConvolutionOut:
      return "convolution.out";
    case OpName::kCopyFrom:
      return "_copy_from";
    case OpName::kCopyFromAndResize:
      return "_copy_from_and_resize";
    case OpName::kCopy_:
      return "copy_";
    case OpName::kCosOut:
      return "cos.out";
    case OpName::kCoshOut:
      return "cosh.out";
    case OpName::kCummaxHelper:
      return "_cummax_helper";
    case OpName::kCumminHelper:
      return "_cummin_helper";
    case OpName::kCumprodOut:
      return "cumprod.out";
    case OpName::kCumsumOut:
      return "cumsum.out";
    case OpName::kCustomKernel:
      return "custom_kernel";
    case OpName::kDetach:
      return "detach";
    case OpName::kDetach_:
      return "detach_";
    case OpName::kDistributedAllGather:
      return "distributed.all_gather";
    case OpName::kDistributedAllGatherIntoTensor:
      return "distributed.all_gather_into_tensor";
    case OpName::kDistributedAllReduce:
      return "distributed.all_reduce";
    case OpName::kDistributedAllToAll:
      return "distributed.all_to_all";
    case OpName::kDistributedAllToAllSingle:
      return "distributed.all_to_all_single";
    case OpName::kDistributedBarrier:
      return "distributed.barrier";
    case OpName::kDistributedBroadcast:
      return "distributed.broadcast";
    case OpName::kDistributedReduceScatter:
      return "distributed.reduce_scatter";
    case OpName::kDistributedReduceScatterTensor:
      return "distributed.reduce_scatter_tensor";
    case OpName::kDistributedReduceScatterTensorCoalesced:
      return "distributed.reduce_scatter_tensor_coalesced";
    case OpName::kDistributedScatter:
      return "distributed.scatter";
    case OpName::kDiv:
      return "div";
    case OpName::kDivOut:
      return "div.out";
    case OpName::kDivOutMode:
      return "div.out_mode";
    case OpName::kDot:
      return "dot";
    case OpName::kDropout:
      return "dropout";
    case OpName::kEluBackwardGradInput:
      return "elu_backward.grad_input";
    case OpName::kEluOut:
      return "elu.out";
    case OpName::kEmbeddingBag:
      return "_embedding_bag";
    case OpName::kEmbeddingBagForwardOnly:
      return "_embedding_bag_forward_only";
    case OpName::kEmbeddingDenseBackward:
      return "embedding_dense_backward";
    case OpName::kEmbeddingRenorm_:
      return "embedding_renorm_";
    case OpName::kEmpty:
      return "empty";
    case OpName::kEmptyStrided:
      return "empty_strided";
    case OpName::kEq:
      return "eq";
    case OpName::kEqOut:
      return "eq.out";
    case OpName::kEqual:
      return "equal";
    case OpName::kErfInvOut:
      return "erfinv.out";
    case OpName::kErfOut:
      return "erf.out";
    case OpName::kExpM1Out:
      return "expm1.out";
    case OpName::kExpOut:
      return "exp.out";
    case OpName::kExponential_:
      return "exponential_";
    case OpName::kFakeQuantizePerTensorAffineCachemask:
      return "fake_quantize_per_tensor_affine_cachemask";
    case OpName::kFftR2c:
      return "_fft_r2c";
    case OpName::kFftR2cOut:
      return "_fft_r2c.out";
    case OpName::kFill_Scalar:
      return "fill_.Scalar";
    case OpName::kFill_Tensor:
      return "fill_.Tensor";
    case OpName::kFlatten:
      return "flatten";
    case OpName::kFlip:
      return "flip";
    case OpName::kFloorDivide:
      return "floor_divide";
    case OpName::kFloorDivideOut:
      return "floor_divide.out";
    case OpName::kFloorDivide_:
      return "floor_divide_";
    case OpName::kFloorDivide_Tensor:
      return "floor_divide_.Tensor";
    case OpName::kFloorOut:
      return "floor.out";
    case OpName::kFmaxOut:
      return "fmax.out";
    case OpName::kFminOut:
      return "fmin.out";
    case OpName::kFmodTensorOut:
      return "fmod.Tensor_out";
    case OpName::kForeachAbs:
      return "_foreach_abs";
    case OpName::kForeachAbs_:
      return "_foreach_abs_";
    case OpName::kForeachAcos:
      return "_foreach_acos";
    case OpName::kForeachAcos_:
      return "_foreach_acos_";
    case OpName::kForeachAddList:
      return "_foreach_add.List";
    case OpName::kForeachAddScalar:
      return "_foreach_add.Scalar";
    case OpName::kForeachAddScalarList:
      return "_foreach_add.ScalarList";
    case OpName::kForeachAddTensor:
      return "_foreach_add.Tensor";
    case OpName::kForeachAdd_List:
      return "_foreach_add_.List";
    case OpName::kForeachAdd_Scalar:
      return "_foreach_add_.Scalar";
    case OpName::kForeachAdd_ScalarList:
      return "_foreach_add_.ScalarList";
    case OpName::kForeachAdd_Tensor:
      return "_foreach_add_.Tensor";
    case OpName::kForeachAddcdivScalar:
      return "_foreach_addcdiv.Scalar";
    case OpName::kForeachAddcdivScalarList:
      return "_foreach_addcdiv.ScalarList";
    case OpName::kForeachAddcdivTensor:
      return "_foreach_addcdiv.Tensor";
    case OpName::kForeachAddcdiv_Scalar:
      return "_foreach_addcdiv_.Scalar";
    case OpName::kForeachAddcdiv_ScalarList:
      return "_foreach_addcdiv_.ScalarList";
    case OpName::kForeachAddcdiv_Tensor:
      return "_foreach_addcdiv_.Tensor";
    case OpName::kForeachAddcmulScalar:
      return "_foreach_addcmul.Scalar";
    case OpName::kForeachAddcmulScalarList:
      return "_foreach_addcmul.ScalarList";
    case OpName::kForeachAddcmulTensor:
      return "_foreach_addcmul.Tensor";
    case OpName::kForeachAddcmul_Scalar:
      return "_foreach_addcmul_.Scalar";
    case OpName::kForeachAddcmul_ScalarList:
      return "_foreach_addcmul_.ScalarList";
    case OpName::kForeachAddcmul_Tensor:
      return "_foreach_addcmul_.Tensor";
    case OpName::kForeachAsin:
      return "_foreach_asin";
    case OpName::kForeachAsin_:
      return "_foreach_asin_";
    case OpName::kForeachAtan:
      return "_foreach_atan";
    case OpName::kForeachAtan_:
      return "_foreach_atan_";
    case OpName::kForeachCeil:
      return "_foreach_ceil";
    case OpName::kForeachCeil_:
      return "_foreach_ceil_";
    case OpName::kForeachClampMaxList:
      return "_foreach_clamp_max.List";
    case OpName::kForeachClampMaxScalar:
      return "_foreach_clamp_max.Scalar";
    case OpName::kForeachClampMaxScalarList:
      return "_foreach_clamp_max.ScalarList";
    case OpName::kForeachClampMax_List:
      return "_foreach_clamp_max_.List";
    case OpName::kForeachClampMax_Scalar:
      return "_foreach_clamp_max_.Scalar";
    case OpName::kForeachClampMax_ScalarList:
      return "_foreach_clamp_max_.ScalarList";
    case OpName::kForeachClampMinList:
      return "_foreach_clamp_min.List";
    case OpName::kForeachClampMinScalar:
      return "_foreach_clamp_min.Scalar";
    case OpName::kForeachClampMinScalarList:
      return "_foreach_clamp_min.ScalarList";
    case OpName::kForeachClampMin_List:
      return "_foreach_clamp_min_.List";
    case OpName::kForeachClampMin_Scalar:
      return "_foreach_clamp_min_.Scalar";
    case OpName::kForeachClampMin_ScalarList:
      return "_foreach_clamp_min_.ScalarList";
    case OpName::kForeachCopy_:
      return "_foreach_copy_";
    case OpName::kForeachCos:
      return "_foreach_cos";
    case OpName::kForeachCos_:
      return "_foreach_cos_";
    case OpName::kForeachCosh:
      return "_foreach_cosh";
    case OpName::kForeachCosh_:
      return "_foreach_cosh_";
    case OpName::kForeachDivList:
      return "_foreach_div.List";
    case OpName::kForeachDivScalar:
      return "_foreach_div.Scalar";
    case OpName::kForeachDivScalarList:
      return "_foreach_div.ScalarList";
    case OpName::kForeachDivTensor:
      return "_foreach_div.Tensor";
    case OpName::kForeachDiv_List:
      return "_foreach_div_.List";
    case OpName::kForeachDiv_Scalar:
      return "_foreach_div_.Scalar";
    case OpName::kForeachDiv_ScalarList:
      return "_foreach_div_.ScalarList";
    case OpName::kForeachDiv_Tensor:
      return "_foreach_div_.Tensor";
    case OpName::kForeachErf:
      return "_foreach_erf";
    case OpName::kForeachErf_:
      return "_foreach_erf_";
    case OpName::kForeachErfc:
      return "_foreach_erfc";
    case OpName::kForeachErfc_:
      return "_foreach_erfc_";
    case OpName::kForeachExp:
      return "_foreach_exp";
    case OpName::kForeachExp_:
      return "_foreach_exp_";
    case OpName::kForeachExpm1:
      return "_foreach_expm1";
    case OpName::kForeachExpm1_:
      return "_foreach_expm1_";
    case OpName::kForeachFloor:
      return "_foreach_floor";
    case OpName::kForeachFloor_:
      return "_foreach_floor_";
    case OpName::kForeachFrac:
      return "_foreach_frac";
    case OpName::kForeachFrac_:
      return "_foreach_frac_";
    case OpName::kForeachLerpList:
      return "_foreach_lerp.List";
    case OpName::kForeachLerpScalar:
      return "_foreach_lerp.Scalar";
    case OpName::kForeachLerpScalarList:
      return "_foreach_lerp.ScalarList";
    case OpName::kForeachLerp_List:
      return "_foreach_lerp_.List";
    case OpName::kForeachLerp_Scalar:
      return "_foreach_lerp_.Scalar";
    case OpName::kForeachLerp_ScalarList:
      return "_foreach_lerp_.ScalarList";
    case OpName::kForeachLgamma:
      return "_foreach_lgamma";
    case OpName::kForeachLgamma_:
      return "_foreach_lgamma_";
    case OpName::kForeachLog10:
      return "_foreach_log10";
    case OpName::kForeachLog10_:
      return "_foreach_log10_";
    case OpName::kForeachLog1p:
      return "_foreach_log1p";
    case OpName::kForeachLog1p_:
      return "_foreach_log1p_";
    case OpName::kForeachLog2:
      return "_foreach_log2";
    case OpName::kForeachLog2_:
      return "_foreach_log2_";
    case OpName::kForeachLog:
      return "_foreach_log";
    case OpName::kForeachLog_:
      return "_foreach_log_";
    case OpName::kForeachMax:
      return "_foreach_max";
    case OpName::kForeachMaximumList:
      return "_foreach_maximum.List";
    case OpName::kForeachMaximumScalar:
      return "_foreach_maximum.Scalar";
    case OpName::kForeachMaximumScalarList:
      return "_foreach_maximum.ScalarList";
    case OpName::kForeachMaximum_List:
      return "_foreach_maximum_.List";
    case OpName::kForeachMaximum_Scalar:
      return "_foreach_maximum_.Scalar";
    case OpName::kForeachMaximum_ScalarList:
      return "_foreach_maximum_.ScalarList";
    case OpName::kForeachMinimumList:
      return "_foreach_minimum.List";
    case OpName::kForeachMinimumScalar:
      return "_foreach_minimum.Scalar";
    case OpName::kForeachMinimumScalarList:
      return "_foreach_minimum.ScalarList";
    case OpName::kForeachMinimum_List:
      return "_foreach_minimum_.List";
    case OpName::kForeachMinimum_Scalar:
      return "_foreach_minimum_.Scalar";
    case OpName::kForeachMinimum_ScalarList:
      return "_foreach_minimum_.ScalarList";
    case OpName::kForeachMulList:
      return "_foreach_mul.List";
    case OpName::kForeachMulScalar:
      return "_foreach_mul.Scalar";
    case OpName::kForeachMulScalarList:
      return "_foreach_mul.ScalarList";
    case OpName::kForeachMulTensor:
      return "_foreach_mul.Tensor";
    case OpName::kForeachMul_List:
      return "_foreach_mul_.List";
    case OpName::kForeachMul_Scalar:
      return "_foreach_mul_.Scalar";
    case OpName::kForeachMul_ScalarList:
      return "_foreach_mul_.ScalarList";
    case OpName::kForeachMul_Tensor:
      return "_foreach_mul_.Tensor";
    case OpName::kForeachNeg:
      return "_foreach_neg";
    case OpName::kForeachNeg_:
      return "_foreach_neg_";
    case OpName::kForeachNormScalar:
      return "_foreach_norm.Scalar";
    case OpName::kForeachPowList:
      return "_foreach_pow.List";
    case OpName::kForeachPowScalar:
      return "_foreach_pow.Scalar";
    case OpName::kForeachPowScalarAndTensor:
      return "_foreach_pow.ScalarAndTensor";
    case OpName::kForeachPowScalarList:
      return "_foreach_pow.ScalarList";
    case OpName::kForeachPow_List:
      return "_foreach_pow_.List";
    case OpName::kForeachPow_Scalar:
      return "_foreach_pow_.Scalar";
    case OpName::kForeachPow_ScalarList:
      return "_foreach_pow_.ScalarList";
    case OpName::kForeachReciprocal:
      return "_foreach_reciprocal";
    case OpName::kForeachReciprocal_:
      return "_foreach_reciprocal_";
    case OpName::kForeachRound:
      return "_foreach_round";
    case OpName::kForeachRound_:
      return "_foreach_round_";
    case OpName::kForeachRsqrt:
      return "_foreach_rsqrt";
    case OpName::kForeachRsqrt_:
      return "_foreach_rsqrt_";
    case OpName::kForeachSigmoid:
      return "_foreach_sigmoid";
    case OpName::kForeachSigmoid_:
      return "_foreach_sigmoid_";
    case OpName::kForeachSign:
      return "_foreach_sign";
    case OpName::kForeachSign_:
      return "_foreach_sign_";
    case OpName::kForeachSin:
      return "_foreach_sin";
    case OpName::kForeachSin_:
      return "_foreach_sin_";
    case OpName::kForeachSinh:
      return "_foreach_sinh";
    case OpName::kForeachSinh_:
      return "_foreach_sinh_";
    case OpName::kForeachSqrt:
      return "_foreach_sqrt";
    case OpName::kForeachSqrt_:
      return "_foreach_sqrt_";
    case OpName::kForeachSubList:
      return "_foreach_sub.List";
    case OpName::kForeachSubScalar:
      return "_foreach_sub.Scalar";
    case OpName::kForeachSubScalarList:
      return "_foreach_sub.ScalarList";
    case OpName::kForeachSub_List:
      return "_foreach_sub_.List";
    case OpName::kForeachSub_Scalar:
      return "_foreach_sub_.Scalar";
    case OpName::kForeachSub_ScalarList:
      return "_foreach_sub_.ScalarList";
    case OpName::kForeachTan:
      return "_foreach_tan";
    case OpName::kForeachTan_:
      return "_foreach_tan_";
    case OpName::kForeachTanh:
      return "_foreach_tanh";
    case OpName::kForeachTanh_:
      return "_foreach_tanh_";
    case OpName::kForeachTrunc:
      return "_foreach_trunc";
    case OpName::kForeachTrunc_:
      return "_foreach_trunc_";
    case OpName::kForeachZero_:
      return "_foreach_zero_";
    case OpName::kFusedRmsNorm:
      return "_fused_rms_norm";
    case OpName::kFusedRmsNormBackward:
      return "_fused_rms_norm_backward";
    case OpName::kFusedSdpChoice:
      return "_fused_sdp_choice";
    case OpName::kGather:
      return "gather";
    case OpName::kGatherOut:
      return "gather.out";
    case OpName::kGe:
      return "ge";
    case OpName::kGeOut:
      return "ge.out";
    case OpName::kGeluBackwardGradInput:
      return "gelu_backward.grad_input";
    case OpName::kGeluOut:
      return "gelu.out";
    case OpName::kGetDimensionSize:
      return "get_dimension_size";
    case OpName::kGridSampler2d:
      return "grid_sampler_2d";
    case OpName::kGridSampler3d:
      return "grid_sampler_3d";
    case OpName::kGt:
      return "gt";
    case OpName::kGtOut:
      return "gt.out";
    case OpName::kHardswish:
      return "hardswish";
    case OpName::kHardswishBackward:
      return "hardswish_backward";
    case OpName::kHardswishOut:
      return "hardswish.out";
    case OpName::kHardswish_:
      return "hardswish_";
    case OpName::kHardtanh:
      return "hardtanh";
    case OpName::kHardtanhOut:
      return "hardtanh.out";
    case OpName::kHardtanh_:
      return "hardtanh_";
    case OpName::kHistc:
      return "histc";
    case OpName::kHistcBounds:
      return "histc_bounds";
    case OpName::kHistcOut:
      return "histc.out";
    case OpName::kIlshiftScalar:
      return "__ilshift__.Scalar";
    case OpName::kIlshiftTensor:
      return "__ilshift__.Tensor";
    case OpName::kIndexAdd:
      return "index_add";
    case OpName::kIndexAddOut:
      return "index_add.out";
    case OpName::kIndexCopyOut:
      return "index_copy.out";
    case OpName::kIndexPutImpl_:
      return "_index_put_impl_";
    case OpName::kIndexSelect:
      return "index_select";
    case OpName::kIndexTensorOut:
      return "index.Tensor_out";
    case OpName::kIrshiftScalar:
      return "__irshift__.Scalar";
    case OpName::kIrshiftTensor:
      return "__irshift__.Tensor";
    case OpName::kIsInScalarTensorOut:
      return "isin.ScalarTensor_out";
    case OpName::kIsInTensorScalarOut:
      return "isin.TensorScalar_out";
    case OpName::kIsInTensorTensorOut:
      return "isin.TensorTensor_out";
    case OpName::kIsNan:
      return "isnan";
    case OpName::kIsNegInfOut:
      return "isneginf.out";
    case OpName::kIsPosInfOut:
      return "isposinf.out";
    case OpName::kLayerNorm:
      return "layer_norm";
    case OpName::kLayerNormBackward:
      return "native_layer_norm_backward";
    case OpName::kLe:
      return "le";
    case OpName::kLeOut:
      return "le.out";
    case OpName::kLeakyReluOut:
      return "leaky_relu.out";
    case OpName::kLerpScalarOut:
      return "lerp.Scalar_out";
    case OpName::kLerpTensorOut:
      return "lerp.Tensor_out";
    case OpName::kLgammaOut:
      return "lgamma.out";
    case OpName::kLiftFreshOut:
      return "liftfresh.out";
    case OpName::kLinalgInvExOut:
      return "linalg_inv_ex.inverse";
    case OpName::kLinalgLuFactorExOut:
      return "linalg_lu_factor_ex.out";
    case OpName::kLinalgLuOut:
      return "linalg_lu.out";
    case OpName::kLinalgLuSolveOut:
      return "linalg_lu_solve.out";
    case OpName::kLinalgSolveExOut:
      return "_linalg_solve_ex.result";
    case OpName::kLinalgSolveTriangular:
      return "linalg_solve_triangular";
    case OpName::kLinalgSolveTriangularOut:
      return "linalg_solve_triangular.out";
    case OpName::kLinalgVectorNormOut:
      return "linalg_vector_norm.out";
    case OpName::kLocalScalarDense:
      return "_local_scalar_dense";
    case OpName::kLog10Out:
      return "log10.out";
    case OpName::kLog1pOut:
      return "log1p.out";
    case OpName::kLog2Out:
      return "log2.out";
    case OpName::kLogOut:
      return "log.out";
    case OpName::kLogSoftmaxBackwardDataOut:
      return "_log_softmax_backward_data.out";
    case OpName::kLogSoftmaxOut:
      return "_log_softmax.out";
    case OpName::kLogicalAndOut:
      return "logical_and.out";
    case OpName::kLogicalNotOut:
      return "logical_not.out";
    case OpName::kLogicalOrOut:
      return "logical_or.out";
    case OpName::kLogicalXorOut:
      return "logical_xor.out";
    case OpName::kLshiftScalar:
      return "__lshift__.Scalar";
    case OpName::kLshiftTensor:
      return "__lshift__.Tensor";
    case OpName::kLt:
      return "lt";
    case OpName::kLtOut:
      return "lt.out";
    case OpName::kLuUnpackOut:
      return "lu_unpack.out";
    case OpName::kMaskedFill_Scalar:
      return "masked_fill_.Scalar";
    case OpName::kMaskedFill_Tensor:
      return "masked_fill_.Tensor";
    case OpName::kMaskedScatter_:
      return "masked_scatter_";
    case OpName::kMaskedSelect:
      return "masked_select";
    case OpName::kMaskedSelectSize:
      return "masked_select_size";
    case OpName::kMax:
      return "max";
    case OpName::kMaxDimMax:
      return "max.dim_max";
    case OpName::kMaxPool2dWithIndicesBackwardGradInput:
      return "max_pool2d_with_indices_backward.grad_input";
    case OpName::kMaxPool2dWithIndicesOut:
      return "max_pool2d_with_indices.out";
    case OpName::kMaxPool3dWithIndices:
      return "max_pool3d_with_indices";
    case OpName::kMaxPool3dWithIndicesBackward:
      return "max_pool3d_with_indices_backward";
    case OpName::kMaxPool3dWithIndicesBackwardGradInput:
      return "max_pool3d_with_indices_backward.grad_input";
    case OpName::kMaxPool3dWithIndicesOut:
      return "max_pool3d_with_indices.out";
    case OpName::kMaxUnaryOut:
      return "max.unary_out";
    case OpName::kMaximum:
      return "maximum";
    case OpName::kMaximumOut:
      return "maximum.out";
    case OpName::kMeanOut:
      return "mean.out";
    case OpName::kMin:
      return "min";
    case OpName::kMinDimMin:
      return "min.dim_min";
    case OpName::kMinUnaryOut:
      return "min.unary_out";
    case OpName::kMinimum:
      return "minimum";
    case OpName::kMinimumOut:
      return "minimum.out";
    case OpName::kMmOut:
      return "mm.out";
    case OpName::kMseLossBackward:
      return "mse_loss_backward";
    case OpName::kMseLossOut:
      return "mse_loss.out";
    case OpName::kMul:
      return "mul";
    case OpName::kMulOut:
      return "mul.out";
    case OpName::kMultinomial:
      return "multinomial";
    case OpName::kMultinomialOut:
      return "multinomial.out";
    case OpName::kNativeBatchNorm:
      return "native_batch_norm";
    case OpName::kNativeBatchNormBackward:
      return "native_batch_norm_backward";
    case OpName::kNativeBatchNormLegit:
      return "_native_batch_norm_legit";
    case OpName::kNativeBatchNormLegitNoStats:
      return "_native_batch_norm_legit.no_stats";
    case OpName::kNativeBatchNormLegitNoStatsOut:
      return "_native_batch_norm_legit.no_stats_out";
    case OpName::kNativeBatchNormLegitOut:
      return "_native_batch_norm_legit.out";
    case OpName::kNativeBatchNormOut:
      return "native_batch_norm.out";
    case OpName::kNativeDropoutBackward:
      return "native_dropout_backward";
    case OpName::kNativeGroupNorm:
      return "native_group_norm";
    case OpName::kNativeGroupNormBackward:
      return "native_group_norm_backward";
    case OpName::kNativeLayerNorm:
      return "native_layer_norm";
    case OpName::kNativeLayerNormBackward:
      return "native_layer_norm_backward";
    case OpName::kNe:
      return "ne";
    case OpName::kNeOut:
      return "ne.out";
    case OpName::kNegOut:
      return "neg.out";
    case OpName::kNllLoss2dForward:
      return "nll_loss2d_forward";
    case OpName::kNllLoss2dForwardOut:
      return "nll_loss2d_forward.output";
    case OpName::kNllLossBackwardGradInput:
      return "nll_loss_backward.grad_input";
    case OpName::kNllLossForwardOut:
      return "nll_loss_forward.output";
    case OpName::kNonzero:
      return "nonzero";
    case OpName::kNonzeroOut:
      return "nonzero.out";
    case OpName::kNonzeroSize:
      return "nonzero_size";
    case OpName::kNormalFloatTensor:
      return "normal.float_Tensor";
    case OpName::kNormalFloatTensorOut:
      return "normal.float_Tensor_out";
    case OpName::kNormalTensorFloat:
      return "normal.Tensor_float";
    case OpName::kNormalTensorFloatOut:
      return "normal.Tensor_float_out";
    case OpName::kNormalTensorTensor:
      return "normal.Tensor_Tensor";
    case OpName::kNormalTensorTensorOut:
      return "normal.Tensor_Tensor_out";
    case OpName::kNormal_:
      return "normal_";
    case OpName::kNotOut:
      return "not.out";
    case OpName::kPadUninitialized_:
      return "pad_uninitialized_";
    case OpName::kPdistForward:
      return "_pdist_forward";
    case OpName::kPolarOut:
      return "polar.out";
    case OpName::kPow:
      return "pow";
    case OpName::kPowOut:
      return "pow.out";
    case OpName::kProd:
      return "prod";
    case OpName::kProdDimOut:
      return "prod.int_out";
    case OpName::kRaggedDot:
      return "ragged_dot";
    case OpName::kRandom_:
      return "random_";
    case OpName::kRandom_From:
      return "random_.from";
    case OpName::kRandom_To:
      return "random_.to";
    case OpName::kRandpermGeneratorOut:
      return "randperm.generator_out";
    case OpName::kReciprocalOut:
      return "reciprocal.out";
    case OpName::kReflectionPad1dBackwardGradInput:
      return "reflection_pad1d_backward.grad_input";
    case OpName::kReflectionPad1dOut:
      return "reflection_pad1d.out";
    case OpName::kReflectionPad2d:
      return "reflection_pad2d";
    case OpName::kReflectionPad2dBackward:
      return "reflection_pad2d_backward";
    case OpName::kReflectionPad2dBackwardGradInput:
      return "reflection_pad2d_backward.grad_input";
    case OpName::kReflectionPad2dOut:
      return "reflection_pad2d.out";
    case OpName::kReflectionPad3dBackwardGradInput:
      return "reflection_pad3d_backward.grad_input";
    case OpName::kReflectionPad3dOut:
      return "reflection_pad3d.out";
    case OpName::kRelu:
      return "relu";
    case OpName::kRelu_:
      return "relu_";
    case OpName::kRemainder:
      return "remainder";
    case OpName::kRemainderOut:
      return "remainder.out";
    case OpName::kRepeat:
      return "repeat";
    case OpName::kReplicationPad1dBackwardGradInput:
      return "replication_pad1d_backward.grad_input";
    case OpName::kReplicationPad1dOut:
      return "replication_pad1d.out";
    case OpName::kReplicationPad2dBackward:
      return "replication_pad2d_backward";
    case OpName::kReplicationPad2dBackwardGradInput:
      return "replication_pad2d_backward.grad_input";
    case OpName::kReplicationPad2dOut:
      return "replication_pad2d.out";
    case OpName::kReplicationPad3dBackward:
      return "replication_pad3d_backward";
    case OpName::kReplicationPad3dBackwardGradInput:
      return "replication_pad3d_backward.grad_input";
    case OpName::kReplicationPad3dOut:
      return "replication_pad3d.out";
    case OpName::kReshapeAlias:
      return "_reshape_alias";
    case OpName::kResize_:
      return "resize_";
    case OpName::kRmsNorm:
      return "rms_norm";
    case OpName::kRngSeed:
      return "seed";
    case OpName::kRngSetOffset:
      return "set_offset";
    case OpName::kRngSetSeed:
      return "set_current_seed";
    case OpName::kRngStateUpdate:
      return "rng_state_update";
    case OpName::kRoll:
      return "roll";
    case OpName::kRound:
      return "round";
    case OpName::kRoundDecimalsOut:
      return "round.decimals_out";
    case OpName::kRoundOut:
      return "round.out";
    case OpName::kRshiftScalar:
      return "__rshift__.Scalar";
    case OpName::kRshiftTensor:
      return "__rshift__.Tensor";
    case OpName::kRsqrOut:
      return "rsqr.out";
    case OpName::kRsub:
      return "rsub";
    case OpName::kScalarTensor:
      return "scalar_tensor";
    case OpName::kScaledDotProductEfficientAttention:
      return "_scaled_dot_product_efficient_attention";
    case OpName::kScaledDotProductFlashAttention:
      return "_scaled_dot_product_flash_attention";
    case OpName::kScaledDotProductFusedAttentionOverrideable:
      return "_scaled_dot_product_fused_attention_overrideable";
    case OpName::kScaledDotProductFusedAttentionOverrideableBackward:
      return "_scaled_dot_product_fused_attention_overrideable_backward";
    case OpName::kScatterAddOut:
      return "scatter_add.out";
    case OpName::kScatterReduceOut:
      return "scatter.reduce_out";
    case OpName::kScatterSrcOut:
      return "scatter.src_out";
    case OpName::kScatterValueOut:
      return "scatter.value_out";
    case OpName::kScatterValueReduceOut:
      return "scatter.value_reduce_out";
    case OpName::kSetDimensionSize:
      return "set_dimension_size";
    case OpName::kSet_:
      return "set_";
    case OpName::kSet_SourceStorage:
      return "set_.source_Storage";
    case OpName::kSet_SourceStorageOffset:
      return "set_.source_Storage_storage_offset";
    case OpName::kSet_SourceTensor:
      return "set_.source_Tensor";
    case OpName::kSgnOut:
      return "sgn.out";
    case OpName::kSigmoidBackwardGradInput:
      return "sigmoid_backward.grad_input";
    case OpName::kSigmoidOut:
      return "sigmoid.out";
    case OpName::kSignOut:
      return "sign.out";
    case OpName::kSignbitOut:
      return "signbit.out";
    case OpName::kSiluOut:
      return "silu.out";
    case OpName::kSinOut:
      return "sin.out";
    case OpName::kSinhOut:
      return "sinh.out";
    case OpName::kSlice:
      return "slice";
    case OpName::kSoftmaxBackwardDataOut:
      return "_softmax_backward_data.out";
    case OpName::kSoftmaxOut:
      return "_softmax.out";
    case OpName::kSortValuesStable:
      return "sort.values_stable";
    case OpName::kSplitWithSizesCopyOut:
      return "split_with_sizes_copy.out";
    case OpName::kSqrOut:
      return "sqr.out";
    case OpName::kSub:
      return "sub";
    case OpName::kSubOut:
      return "sub.out";
    case OpName::kSum:
      return "sum";
    case OpName::kSumIntListOut:
      return "sum.IntList_out";
    case OpName::kTake:
      return "take";
    case OpName::kTakeOut:
      return "take.out";
    case OpName::kTanOut:
      return "tan.out";
    case OpName::kTanhBackwardGradInput:
      return "tanh_backward.grad_input";
    case OpName::kTanhOut:
      return "tanh.out";
    case OpName::kThresholdBackwardGradInput:
      return "threshold_backward.grad_input";
    case OpName::kThresholdOut:
      return "threshold.out";
    case OpName::kTo:
      return "to";
    case OpName::kToCopy:
      return "_to_copy";
    case OpName::kTopkValues:
      return "topk.values";
    case OpName::kTorchTpuInternalGatherAllSubgroups:
      return "_torchtpu_internal_gather_all_subgroups";
    case OpName::kTrilIndices:
      return "tril_indices";
    case OpName::kTrilOut:
      return "tril.out";
    case OpName::kTriuOut:
      return "triu.out";
    case OpName::kTruncOut:
      return "trunc.out";
    case OpName::kUnfold:
      return "unfold";
    case OpName::kUniform_:
      return "uniform_";
    case OpName::kUnsqueeze:
      return "unsqueeze";
    case OpName::kUnsqueezeCopy:
      return "unsqueeze_copy";
    case OpName::kUnsqueezeCopyOut:
      return "unsqueeze_copy.out";
    case OpName::kUnsqueeze_:
      return "unsqueeze_";
    case OpName::kUntypedStorageResize_:
      return "untyped_storage_resize_";
    case OpName::kUpsampleBilinear2dBackwardGradInput:
      return "upsample_bilinear2d_backward.grad_input";
    case OpName::kUpsampleBilinear2dOut:
      return "upsample_bilinear2d.out";
    case OpName::kUpsampleNearest1dBackwardGradInput:
      return "upsample_nearest1d_backward.grad_input";
    case OpName::kUpsampleNearest1dOut:
      return "upsample_nearest1d.out";
    case OpName::kUpsampleNearest2dBackwardGradInput:
      return "upsample_nearest2d_backward.grad_input";
    case OpName::kUpsampleNearest2dOut:
      return "upsample_nearest2d.out";
    case OpName::kUpsampleNearest3dBackwardGradInput:
      return "upsample_nearest3d_backward.grad_input";
    case OpName::kUpsampleNearest3dOut:
      return "upsample_nearest3d.out";
    case OpName::kUpsampleNearestExact1dBackwardGradInput:
      return "_upsample_nearest_exact1d_backward.grad_input";
    case OpName::kUpsampleNearestExact1dOut:
      return "_upsample_nearest_exact1d.out";
    case OpName::kUpsampleNearestExact2dBackwardGradInput:
      return "_upsample_nearest_exact2d_backward.grad_input";
    case OpName::kUpsampleNearestExact2dOut:
      return "_upsample_nearest_exact2d.out";
    case OpName::kUpsampleNearestExact3dBackwardGradInput:
      return "_upsample_nearest_exact3d_backward.grad_input";
    case OpName::kUpsampleNearestExact3dOut:
      return "_upsample_nearest_exact3d.out";
    case OpName::kVar:
      return "var";
    case OpName::kVarOut:
      return "var.out";
    case OpName::kVdot:
      return "vdot";
    case OpName::kView:
      return "view";
    case OpName::kViewAsComplex:
      return "view_as_complex";
    case OpName::kViewAsReal:
      return "view_as_real";
    case OpName::kWhereSelf:
      return "where.self";
    case OpName::kWhereSelfOut:
      return "where.self_out";
    case OpName::kZero_:
      return "zero_";
      // go/keep-sorted end
      // Deliberately omitting default case to let the C++ compiler enforce that
      // all cases are handled.
  }
}

std::string_view ToBaseName(const OpName op_name) {
  if (op_name == OpName::kIndexPutImpl_) {
    return "index_put_";
  }

  auto full_name = ToString(op_name);
  if (!full_name.empty() && full_name[0] == '_') {
    full_name.remove_prefix(1);
  }

  // Distributed ops are named like "distributed.foo" and base name is the same
  // as the op name.
  if (absl::StartsWith(full_name, "distributed.")) {
    return full_name;
  }
  const auto last_dot_pos = full_name.rfind('.');
  return last_dot_pos == std::string_view::npos
             ? full_name
             : full_name.substr(0, last_dot_pos);
}

}  // namespace torch_tpu
