# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Validates that repository directory layout matches the expected manifests."""

import argparse
import pathlib
import sys
from typing import Final, Iterable

# TODO(b/554114867): Implement symlink-based src folder setup and remove this manifest check.

# Expected direct subdirectories inside src/torch_tpu
EXPECTED_SRC_DIRS: Final[frozenset[str]] = frozenset([
    "_internal",
    "ops",
])

# Expected direct directories at repository root
EXPECTED_ROOT_DIRS: Final[frozenset[str]] = frozenset([
    "bazel",
    "build_files",
    "ci",
    "csrc",
    "docker",
    "docs",
    "examples",
    "requirements",
    "shims",
    "src",
    "tests",
])


# Directories generated by runtime tools, caches, or build processes that should be ignored
IGNORED_DIRS: Final[frozenset[str]] = frozenset([
    "__pycache__",
])


def get_subdirectories(path: pathlib.Path) -> set[str]:
  """Returns non-hidden, non-cache direct subdirectory names."""
  if not path.is_dir():
    return set()
  return {
      p.name
      for p in path.iterdir()
      if p.is_dir()
      and not p.is_symlink()
      and not p.name.startswith(".")
      and p.name not in IGNORED_DIRS
  }


def validate_manifest(
    location_name: str, actual: Iterable[str], expected: frozenset[str]
) -> bool:
  """Compares actual subdirectories against expected manifest."""
  actual_set = set(actual)
  if actual_set == expected:
    return True

  missing = sorted(expected - actual_set)
  unexpected = sorted(actual_set - expected)

  print(
      f"::error::Unexpected directories found in {location_name}",
      file=sys.stderr,
  )
  if missing:
    print(f"Missing expected directories: {missing}", file=sys.stderr)
  if unexpected:
    print(f"Unexpected extra directories: {unexpected}", file=sys.stderr)
  print(f"Expected: {sorted(expected)}", file=sys.stderr)
  print(f"Actual:   {sorted(actual_set)}", file=sys.stderr)
  return False


def validate_directory_layout(repo_root: pathlib.Path) -> bool:
  """Validates both src/torch_tpu and repository root layouts."""
  success = True

  # 1. Validate src/torch_tpu/ directories
  src_dir = repo_root / "src" / "torch_tpu"
  if not src_dir.is_dir():
    print(
        f"::error::Expected directory '{src_dir}' does not exist.",
        file=sys.stderr,
    )
    success = False
  else:
    actual_src = get_subdirectories(src_dir)
    if not validate_manifest("src/torch_tpu/", actual_src, EXPECTED_SRC_DIRS):
      success = False

  # 2. Validate repository root directories
  actual_root = get_subdirectories(repo_root)
  if not validate_manifest("repository root", actual_root, EXPECTED_ROOT_DIRS):
    success = False

  if not success:
    print(
        "Please update EXPECTED_SRC_DIRS / EXPECTED_ROOT_DIRS in "
        "ci/tools/check_directory_layout.py if this change is intentional.",
        file=sys.stderr,
    )

  return success


def _default_repo_root() -> pathlib.Path:
  script_root = pathlib.Path(__file__).resolve().parents[2]
  if (script_root / "ci").is_dir():
    return script_root
  return pathlib.Path.cwd()


def main(argv: list[str] | None = None) -> int:
  parser = argparse.ArgumentParser(
      description="Validate repository directory layout against manifests."
  )
  parser.add_argument(
      "--repo-root",
      type=pathlib.Path,
      default=_default_repo_root(),
      help="Path to the repository root directory.",
  )
  args = parser.parse_args(argv)

  if not validate_directory_layout(args.repo_root):
    return 1

  print("Directory layout validated successfully.")
  return 0


if __name__ == "__main__":
  sys.exit(main())
