# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utilities for building torch_tpu."""

load("//build_files:build_defs.bzl", "torch_tpu_package_end")
load("//shims/build_defs_testing:bzl_library.bzl", "bzl_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//:__subpackages__"],
)

bzl_library(
    name = "build_defs_bzl",
    srcs = ["build_defs.bzl"],
    visibility = ["//visibility:private"],
    deps = [
        "//shims/build_cleaner:build_defs_lib",
        "//shims/py_rules:pytype_bzl",
        "@rules_cc//cc:core_rules",
        "@rules_python//python:py_test_bzl",
        "@xla//third_party/py/rules_pywrap:pywrap.default.bzl",
    ],
)

torch_tpu_package_end()
