# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests of Llama3 as implemented by HuggingFace Transformers."""

from absl import flags
from absl import logging
from absl.testing import absltest
from absl.testing import parameterized
import torch
from torch_tpu._internal.utils import log_utils
from examples import paths
from examples.huggingface_transformers import model_configs
import transformers

log_utils.log_to_stderr()


_DEVICE = flags.DEFINE_enum(
    "device",
    None,
    ["tpu", "cuda", "cpu"],
    required=True,
    help="Accelerator to test.",
)


class SingleAcceleratorSmokeTest(parameterized.TestCase):

  def setUp(self):
    super().setUp()
    # This abstest flag will always be set to an int.
    seed = absltest.FLAGS.test_random_seed
    if seed is None or not isinstance(seed, int):
      raise ValueError("absltest.FLAGS.test_random_seed not an int: %s" % seed)

    torch.manual_seed(seed)
    logging.info("Using absltest.FLAGS.test_random_seed: %d", seed)

    if _DEVICE.value == "tpu":
      from torch_tpu import api  # pylint: disable=g-import-not-at-top

      self.accelerator_device = api.tpu_device()
    elif _DEVICE.value == "cuda":
      self.accelerator_device = torch.device("cuda")
    elif _DEVICE.value == "cpu":
      self.accelerator_device = torch.device("cpu")
    else:
      raise RuntimeError(f"Unexpected flag value: {_DEVICE.value}")

  @parameterized.parameters(model_configs.get_lazy_all_model_configs())
  def test_model_forward(
      self, model_id: str, config_loader: model_configs.ConfigLoader
  ):
    """Smoke test small models on forward pass."""
    config = config_loader()

    # Arrange
    logging.info("Model id: %s", model_id)
    logging.info("Model type: %s", config.model_type)
    logging.info("Hidden size: %s", config.hidden_size)
    logging.info("Number of attention heads: %s", config.num_attention_heads)
    logging.info("Number of layers: %s", config.num_hidden_layers)

    # Act
    logging.info("Loading model %s", model_id)
    # A more modern approach is to set a GPU/TPU as the default device to enable
    # faster model initialization. This code uses the older approach of
    # initializing the model on the CPU and then moving it to the accelerator,
    # to avoid trigger missing ops in the TPU backend because
    # using transformers triggers lazy loading of the package and ultimately
    # ops. See package_load_test for a test of the modern approach.
    model = transformers.AutoModelForCausalLM.from_config(config)
    model = model.to(self.accelerator_device)
    model.eval()
    logging.info("Number of parameters: %s", model.num_parameters())

    inputs = torch.full(
        (2, 3),
        config.bos_token_id,
        dtype=torch.int64,
        device=self.accelerator_device,
    )
    with torch.no_grad():
      # This is NOT the right way to use a model. Inputs should be
      # generated by a tokenizer. But this is good enough for a smoke test.
      output: transformers.CausalLMOutputWithPast = model(inputs)
      logging.info("Output: %s", output)

    # Assert
    # No assert. If there's no crash, it passes.

  @parameterized.parameters(model_configs.get_lazy_mini_model_configs())
  def test_model_backward(
      self, _: str, config_loader: model_configs.ConfigLoader
  ):
    """Smoke test small models on backward pass."""
    # Arrange
    config = config_loader()
    model = transformers.AutoModelForCausalLM.from_config(config)
    model = model.to(self.accelerator_device)
    optimizer = torch.optim.Adam(
        model.parameters(), lr=0.1
    )  # Gigantic LR for testing.

    inputs = torch.full(
        (2, 3),
        config.bos_token_id,
        dtype=torch.int64,
        device=self.accelerator_device,
    )
    targets = torch.full(
        (2, 3),
        42,
        dtype=torch.int64,
        device=self.accelerator_device,
    )

    # Act
    previous_loss = float("inf")
    for epoch in range(5):
      model.train()
      output = model(inputs, labels=targets)
      current_loss = output.loss.cpu()
      logging.info(f"Epoch {epoch}: output.loss: %s", current_loss)
      output.loss.backward()
      optimizer.step()
      optimizer.zero_grad()

      # Assert
      self.assertLess(current_loss.item(), previous_loss)
      previous_loss = current_loss.item()

  def test_backward_sanity(self):
    """Sanity test of backward pass."""
    # Arrange
    model = torch.nn.Linear(10, 10)
    model = model.to(self.accelerator_device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1.0)
    target = torch.tensor([1.0] * 10, dtype=torch.float32)
    target = target.to(self.accelerator_device)
    for _ in range(10):
      model.train()
      output = model(target)
      loss = target - output
      optimizer.step()
      optimizer.zero_grad()

  def test_load_tokenizer_llama3_8B_instruct(self):
    """Test loading Llama tokenizer from storage."""
    tokenizer = transformers.AutoTokenizer.from_pretrained(
        f"{paths.XM_HOME}weights/huggingface/meta-llama/Meta-Llama-3-8B-Instruct/"
    )
    self.assertIsNotNone(tokenizer)


if __name__ == "__main__":
  absltest.main()
