# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Example use of Qwen3 model with KV Cache."""

import copy
import pathlib
import time

from absl import app
from absl import flags
from absl import logging
import torch
import torch._inductor.config as inductor_config
from torch_tpu._internal.compile import _backend
from torch_tpu._internal.utils import log_utils
from examples import paths
import transformers

from torch_tpu._internal.shims.xprof import traceme

log_utils.log_to_stderr()

_MODEL_NAME = flags.DEFINE_string(
    "model_name",
    "Qwen/Qwen3-0.6B",
    "Name of the model to run. For ex: 'Qwen/Qwen3-0.6B', 'Qwen/Qwen3-1.7B',"
    " 'Qwen/Qwen3-4B', 'Qwen/Qwen3-8B', or"
    " 'Qwen/Qwen3-Coder-30B-A3B-Instruct-MINI'.",
)

_DEVICE = flags.DEFINE_string(
    "device",
    "tpu",
    "Device to run the model on. Can be 'tpu' or 'cuda'.",
)

_COMPILE_ONLY = flags.DEFINE_boolean(
    "compile_only",
    True,
    "If True, only do compile mode execution, else also do eager mode"
    " execution.",
)
_USE_RANDOM_WEIGHTS = flags.DEFINE_boolean(
    "use_random_weights",
    False,
    "Whether to initialize model with random weights instead of loading from"
    " checkpoint.",
)


def model_generate(
    model: transformers.PreTrainedModel,
    initial_inputs: torch.Tensor,
    tokenizer: transformers.PreTrainedTokenizer,
    max_decode_steps: int,
    prefix: str = "",
) -> str:
  """Generates text using a model with dynamic KV caching.

  Args:
    model: The language model to use for generation.
    initial_inputs: The initial input tensor for the prefill stage.
    tokenizer: The tokenizer to decode the generated token IDs.
    max_decode_steps: The maximum number of decoding steps to perform.
    prefix: A prefix string to prepend to log messages.

  Returns:
    The decoded text generated by the model.
  """
  with torch.no_grad():
    with traceme.TraceMe(f"[{prefix}] Prefill"):
      start_time = time.time()
      output = model(input_ids=initial_inputs, use_cache=True)
      logits = output.logits.to("cpu")
      past_key_values = output.past_key_values
      end_time = time.time()

    prefill_time = end_time - start_time
    print(f"{prefix} Prefill time: {prefill_time * 1000:.2f} ms")
    output_tokens = initial_inputs.to("cpu")
    next_token = None
    start_time = time.time()
    steps_completed = 0
    for i in range(max_decode_steps):
      if next_token == 0:
        break
      # greedy sampling
      next_token_cpu = torch.argmax(logits[:, -1, :], dim=-1).unsqueeze(-1)
      output_tokens = torch.cat([output_tokens, next_token_cpu], dim=1)

      next_token = next_token_cpu.to(model.device)
      with traceme.TraceMe(f"[{prefix}] Decode step {i + 1}"):
        prev_time = time.time()
        output = model(
            input_ids=next_token,
            past_key_values=past_key_values,
            use_cache=True,
        )
        logits = output.logits.to("cpu")
        current_time = time.time()
      print(
          f"{prefix} Decode step {i + 1}:"
          f" {(current_time - prev_time) * 1000:.2f} ms,"
          f" device={model.device}"
      )
      past_key_values = output.past_key_values
      steps_completed += 1

    end_time = time.time()
    decode_time = end_time - start_time
    if steps_completed > 0:
      print(
          f"{prefix} Decode time per token:"
          f" {decode_time * 1000 / steps_completed:.2f} ms"
      )
    else:
      print(f"{prefix} No decode steps were run.")
  output = output_tokens
  output_list = output.tolist()
  output_text = tokenizer.decode(output_list[0], skip_special_tokens=True)
  return output_text


def _run_with_actual_weights(
    tokenizer: transformers.PreTrainedTokenizer,
    model_path: pathlib.Path,
    inputs: torch.Tensor,
    max_decode_steps: int,
    device: str,
) -> None:
  if device == "cuda":
    inductor_config.compile_threads = 1

  # Load CPU model from HuggingFace
  model_cpu = transformers.AutoModelForCausalLM.from_pretrained(
      model_path, torch_dtype=torch.bfloat16, attn_implementation="eager"
  )
  # Copy the CPU model and move it to the target device
  model_device = copy.deepcopy(model_cpu).to(device)
  output_cpu = model_generate(
      model_cpu, inputs, tokenizer, max_decode_steps, prefix="[CPU] "
  )
  logging.info("output_cpu=%s", output_cpu)

  if not _COMPILE_ONLY.value:
    output_device = model_generate(
        model_device,
        inputs.to(device),
        tokenizer,
        max_decode_steps,
        prefix=f"[{device.upper()}] ",
    )
    logging.info("output_%s=%s", device, output_device)
    assert output_cpu == output_device

  if device == "cuda":
    model_device_compiled = torch.compile(model_device, backend="inductor")
  else:
    model_device_compiled = torch.compile(
        model_device, backend=_backend.TpuBackend(dynamism=True)
    )
  output_device_compiled = model_generate(
      model_device_compiled,
      inputs.to(device),
      tokenizer,
      max_decode_steps,
      prefix=f"[Compiled {device.upper()}] ",
  )
  logging.info("output_%s_compiled=%s", device, output_device_compiled)
  assert output_cpu == output_device_compiled


def _run_with_random_weights(
    tokenizer: transformers.PreTrainedTokenizer,
    model_path: pathlib.Path,
    inputs: torch.Tensor,
    max_decode_steps: int,
    device: str,
) -> None:
  if device == "cuda":
    inductor_config.compile_threads = 1
  config = transformers.AutoConfig.from_pretrained(model_path)
  config._attn_implementation = "eager"

  with torch.device(device):
    model_device = transformers.AutoModelForCausalLM.from_config(config).to(
        torch.bfloat16
    )

  if device == "cuda":
    model_device_compiled = torch.compile(model_device)
  else:
    model_device_compiled = torch.compile(
        model_device, backend=_backend.TpuBackend(dynamism=True)
    )

  output_device_compiled = model_generate(
      model_device_compiled,
      inputs.to(device),
      tokenizer,
      max_decode_steps,
      prefix=f"[Compiled {device.upper()}] ",
  )
  logging.info("output_%s_compiled=%s", device, output_device_compiled)


# pylint: disable=unused-argument
def main(argv):
  torch.manual_seed(123)

  # All Qwen3 models (from 0.6B up to 30B MoE) share the exact same
  # tokenizer vocabulary. Also, not every model has its own separate
  # tokenizer files, hence using the base 0.6B model for tokenizer.
  tokenizer_path = (
      pathlib.Path(paths.XM_HOME)
      / "weights"
      / "huggingface"
      / "Qwen/Qwen3-0.6B"
  )

  model_path = (
      pathlib.Path(paths.XM_HOME)
      / "weights"
      / "huggingface"
      / _MODEL_NAME.value
  )

  # Load tokenizer from HuggingFace
  tokenizer = transformers.AutoTokenizer.from_pretrained(tokenizer_path)

  text = "Who are you?"
  messages = [{"role": "user", "content": text}]
  inputs = tokenizer.apply_chat_template(
      messages,
      add_generation_prompt=True,
      tokenize=True,
      return_dict=True,
      return_tensors="pt",
  ).input_ids

  max_decode_steps = 10

  if _USE_RANDOM_WEIGHTS.value:
    _run_with_random_weights(
        tokenizer, model_path, inputs, max_decode_steps, _DEVICE.value
    )
  else:
    _run_with_actual_weights(
        tokenizer, model_path, inputs, max_decode_steps, _DEVICE.value
    )


if __name__ == "__main__":
  app.run(main)
