# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests of Llama3 as implemented by HuggingFace Transformers."""

from absl import flags
from absl import logging
from absl.testing import absltest
import torch
from torch_tpu._internal.utils import log_utils
from examples.huggingface_transformers import model_configs
import transformers

log_utils.log_to_stderr()


_DEVICE = flags.DEFINE_enum(
    "device",
    None,
    ["tpu", "cuda", "xla_cuda"],
    required=True,
    help="Accelerator to test.",
)


class SingleAcceleratorSmokeTest(absltest.TestCase):

  def setUp(self):
    super().setUp()
    # This abstest flag will always be set to an int.
    seed = absltest.FLAGS.test_random_seed
    if seed is None or not isinstance(seed, int):
      raise ValueError("absltest.FLAGS.test_random_seed not an int: %s" % seed)

    torch.manual_seed(seed)
    logging.info("Using absltest.FLAGS.test_random_seed: %d", seed)

    if _DEVICE.value == "tpu":
      from torch_tpu import api  # pylint: disable=g-import-not-at-top

      self.accelerator_device = api.tpu_device()
    elif _DEVICE.value == "xla_cuda":
      from torch_tpu import api  # pylint: disable=g-import-not-at-top

      self.accelerator_device = api._xla_cuda_device()
    elif _DEVICE.value == "cuda":
      self.accelerator_device = torch.device("cuda:0")
    else:
      raise RuntimeError(f"Unexpected flag value: {_DEVICE.value}")

  def test_forward(self):
    """Test Qwen3 0.6B model on various shapes."""
    batch_size = 4
    seq_len = 2**12
    # Arrange
    config = model_configs.create_config_loader("Qwen/Qwen3-0.6B")()
    model = transformers.AutoModelForCausalLM.from_config(config)
    model = model.to(self.accelerator_device)
    model.eval()

    inputs = torch.full(
        (batch_size, seq_len),
        config.bos_token_id,
        dtype=torch.int64,
        device=self.accelerator_device,
    )

    # Act
    with torch.no_grad():
      # This is NOT the right way to use a model. Inputs should be
      # generated by a tokenizer. But good enough for this test.
      result: transformers.CausalLMOutputWithPast = model(inputs)
    # This forces the equivalent of torch.cuda.synchronize().
    _ = result.logits.cpu()

    # Assert
    # No assert. If there's no crash, it passes.
    logging.info(
        "Qwen3 0.6B forward test passed with batch size %d and seq len %d",
        batch_size,
        seq_len,
    )
    logging.flush()


if __name__ == "__main__":
  absltest.main()
