# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Utilities for SPMD execution in torch_tpu."""

from collections.abc import Callable
import functools
from typing import Any, TypeVar

import torch
from torch.utils import _pytree
from torch_tpu._internal.distributed import tpu_distributed
from torch_tpu._internal.sync import sync

_F = TypeVar("_F", bound=Callable[..., Any])

SPMD_SAFE_METADATA_KEY = "spmd_safe"


def _synchronize_tensors(args, kwargs):
  flat_args, _ = _pytree.tree_flatten((args, kwargs))
  tensors = [
      t
      for t in flat_args
      if isinstance(t, torch.Tensor) and t.device.type != "cpu"
  ]
  if tensors:
    sync.synchronize(tensors, wait=False)


def spmd_safe(func: _F) -> _F:
  """Decorator that allows users to mark a function as SPMD safe.

  This decorator calls `sync.synchronize(wait=False)` on all input and output
  tensors of the function which ensures no outside operations can get fused into
  the execution graphs generated by the function.
  The decorator marks entry and exit of a SPMD safe region which enables fat
  collectives for the graph generated by the function overriding the
  `TORCH_TPU_INTERNAL_MATERIALIZE_COLLECTIVE_TENSORS` environment variable when
  set.

  Args:
    func: The function to decorate.

  Returns:
    The decorated function.

  Example:
    @spmd_safe
    def my_func(x: torch.Tensor) -> torch.Tensor:
      y = x * 5
      dist.all_reduce(y)
      return y
  """

  @functools.wraps(func)
  def wrapper(*args: Any, **kwargs: Any) -> Any:
    is_compiling = torch.compiler.is_compiling()

    if not is_compiling:
      _synchronize_tensors(args, kwargs)

      tpu_distributed.enter_spmd_safe_region()
      try:
        result = func(*args, **kwargs)
      finally:
        tpu_distributed.exit_spmd_safe_region()

      _synchronize_tensors(result, {})
      return result

    # In compile mode, annotate the FX tracing context with spmd_safe metadata.
    with torch.fx.traceback.annotate({SPMD_SAFE_METADATA_KEY: True}):
      return func(*args, **kwargs)

  return wrapper  # pytype: disable=bad-return-type
