# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Test Wheels

on:
  # Enable remote connections for workflow dispatch to enable halting.
  # See go/ml-github-actions:connect#enable-workflow-dispatch.
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: "Should this workflow run wait for a remote connection?"
        type: choice
        default: "no"
        options:
          - "yes"
          - "no"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *' # 1 AM PST

# Cancel old jobs when they are replaced by new runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # Don't cancel in-progress jobs for main branch
  cancel-in-progress: ${{ github.ref != 'main' }}

jobs:
  # TODO(pganssle): Migrate to cibuildwheel
  build_wheels:
    name: "Build wheel on ${{ matrix.job_info.runner }}"
    strategy:
      matrix:
        job_info:
          [
            {
              runner: "linux-x86-n2-16",
              container: "us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest",
            },
          ]
    # Use self-hosted runners. For a Linux runner, a corresponding container image used for the
    # workflow is required.
    # See go/ml-github-actions/getting_started/using_runners.md#supported-runner-scale-set.
    runs-on: ${{ matrix.job_info.runner }}
    container:
      image: ${{ matrix.job_info.container }}
    env:
      WHEEL_DIR: dist
    outputs:
      gcs-path: ${{ steps.vars.outputs.gcs_path }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - id: vars
        run: echo "gcs_path=gs://torch-tpu-ci-transient/artifacts/${{ github.workflow }}/${{ github.run_number }}/${{ github.run_attempt }}" >> $GITHUB_OUTPUT
      - name: Build wheel
        run: |
          bazel build --config=remote_caching_readonly --config=remote_execution_readonly //ci/wheel:torch_tpu_wheel --define WHEEL_VERSION_EXTRAS=.dev$(date +%Y%m%d%H%M%S)
          mkdir $WHEEL_DIR
          cp bazel-bin/ci/wheel/*.whl $WHEEL_DIR
      - name: Upload wheel to GCS for wheel testing
        if: github.event_name != 'schedule'
        run:  gcloud storage cp -r "$(pwd)/$WHEEL_DIR/*.whl" "gs://torch-tpu-ci-transient/artifacts/${{ github.workflow }}/${{ github.run_number }}/${{ github.run_attempt }}/"
      - name: Upload to Artifact Registry
        # Run only on main branch, once a day.
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          # Install package needed to authenticate to artifactregistry for Python.
          # See https://cloud.google.com/artifact-registry/docs/python/authentication
          pip install keyrings.google-artifactregistry-auth

          # Configure pypirc for twine upload.
          pypirc_content=$(cat <<EOF
          [distutils]
          index-servers =
              torch-tpu-testing-repo

          [torch-tpu-testing-repo]
          repository = https://us-python.pkg.dev/ml-oss-artifacts-transient/torch-tpu-testing-registry/
          EOF
          )
          echo "$pypirc_content" > "$HOME"/.pypirc

          python3 -m twine upload --repository-url https://us-python.pkg.dev/ml-oss-artifacts-transient/torch-tpu-testing-registry $WHEEL_DIR/torch_tpu-*.whl

  test_wheels:
    name: Test wheel on ${{ matrix.runner }}
    if: github.event_name != 'schedule'
    needs: build_wheels
    strategy:
      matrix:
        include:
          - name: CPU
            runner: linux-x86-n2-16
            extra_flags: "--config=wheel_test_cpu"
          - name: TPU
            runner: linux-x86-ct5lp-224-8tpu
            extra_flags: '--config=wheel_test_tpu --run_under="$(pwd)/ci/tools/parallel_accelerator_execute.sh"'
    runs-on: ${{ matrix.runner }}
    container:
      image: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest
      options: --privileged
    permissions:
      contents: read
      pull-requests: read
      issues: read
    steps:
      - uses: actions/checkout@v5
      - name: Download Wheel from GCS
        run: |
          mkdir dist
          gcloud storage cp "${{ needs.build_wheels.outputs.gcs-path }}/*.whl" dist/
      - name: Wait For Connection
        uses: google-ml-infra/actions/ci_connection@08e5394bb8179c66a50ac783fb8b2501a034c06f
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
      - name: Run tests
        shell: bash
        run: bazel test ${{ matrix.extra_flags }} //...
