# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Nightly Benchmarks

on:
  # Allow manual runs from the Actions tab for testing
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day

permissions:
  contents: read
  pull-requests: write

jobs:
  run_benchmarks:
    name: Run TorchTPU benchmarks
    uses: google-ml-infra/bap/.github/workflows/run-benchmarks.yaml@bd952b0063be0b4169f698947792d203ab5f5c42 # main
    with:
      registry_file: "examples/benchmarks/benchmark_registry.pbtxt"
      bap_ref: "bd952b0063be0b4169f698947792d203ab5f5c42"
      publish_metrics: true
      pub_sub_gcp_project_id: "ml-oss-benchmarking-production"
      pub_sub_gcp_topic_id: "private-torch-tpu-prod"
      runner: "linux-x86-n4-16"
