# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI - Postsubmit on TPU

on:
  # Enable remote connections. Add a workflow dispatch to enable halting.
  # See go/ml-github-actions:connect#enable-workflow-dispatch.
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        default: 'no'
        options:
          - 'yes'
          - 'no'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read
  pull-requests: read
  issues: write

# Concurrency for postsubmit:
# We generally want to run every postsubmit to ensure a clean history,
# but if multiple merges happen rapidly, older runs will be cancelled.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  run_tests:
    name: "Postsubmit on ${{ matrix.job_info.runner }}"
    if: >-
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.labels.*.name, 'ci:tpu-postsubmit')
    strategy:
      fail-fast: false
      matrix:
        job_info: [
          {
            runner: "linux-x86-ct6e-180-8tpu",
            bazel_config: "ci_tpu_on_v6",
          },
          {
            runner: "linux-x86-tpu7x-224-4tpu",
            bazel_config: "ci_tpu_on_v7",
          }
        ]
    # Use self-hosted runners. For a Linux runner, a corresponding container image used for the
    # workflow is required.
    # See go/ml-github-actions/getting_started/using_runners.md#supported-runner-scale-set.
    runs-on: ${{ matrix.job_info.runner }}
    container:
      image: "us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest"
    steps:
      - run: echo "Start running tests."
      # Clone the GitHub repository to runner's environment $GITHUB_WORKSPACE, making its files
      # accessible for workflow to use. Otherwise, the workflow cannot find the files (e.g. ls -lR
      # will return "total 0").
      - uses: actions/checkout@v5
      # Enable remote connections. Add a waiting step.
      # See go/ml-github-actions:connect#add-waiting-step.
      - name: Wait For Connection
        uses: google-ml-infra/actions/ci_connection@08e5394bb8179c66a50ac783fb8b2501a034c06f
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
      # We don't need a separate step for bazel build as bazel test will also build the code before
      # running the tests. This allows test building and test running to overlap and reduce total
      # build time.
      - name: Run Bazel Test
        run: bazel test --config=${{ matrix.job_info.bazel_config }} --run_under="$(pwd)/ci/tools/parallel_accelerator_execute.sh" //...
      - name: Upload Test Logs on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: bazel-testlogs-${{ matrix.job_info.runner }}
          path: bazel-testlogs/
          retention-days: 7

  notify_failure:
    name: Notify Failed Runs
    needs: [run_tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check whether one of the jobs failed
        if: contains(needs.run_tests.result, 'failure') && github.event_name != 'pull_request'
        uses: jayqi/failed-build-issue-action@1a893bbf43ef1c2a8705e2b115cd4f0fe3c5649b  # v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-name: "ci:tpu-postsubmit-failed"
          title-template: "Failed Postsubmit on TPU"
